version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - dyyz1993

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
