/**
 * Generates admin/App.tsx content based on resolved preset
 */
import type { ResolvedPreset } from './template-generator'
import { getAdminPages } from './template-generator'

/**
 * Normalize a manifest admin page route to the admin SPA's internal path
 * (basename `/admin` relative). Manifest routes may carry a redundant
 * `/admin` prefix (e.g. `/admin/categories` from the plugin module); the
 * Sidebar NavLinks and template App both use the unprefixed form.
 */
function normalizeAdminRoute(route: string): string {
  return route.replace(/^\/admin(?=\/)/, '')
}

/**
 * Generates admin/layouts/sidebar-availability.ts content based on resolved preset.
 * Sidebar 据此过滤菜单入口：preset 未包含的模块（如 forum 无 plugin）对应
 * 路由不在列表中，入口被隐藏，避免点击后渲染空白内容区。
 * （文件名避开 *routes*：目录结构校验会把 *routes*.ts 强制归入 routes/）
 */
export function generateAdminSidebarRoutes(resolved: ResolvedPreset): string | null {
  if (!resolved.hasAdmin) return null

  const pages = getAdminPages(resolved) ?? []
  const routes = [
    ...new Set(pages.map(p => normalizeAdminRoute(p.route)).sort((a, b) => a.localeCompare(b))),
  ]

  const lines = routes.map(route => `  '${route}',`)

  return `/**
 * Admin routes available in the current build. GENERATED by the scaffold CLI
 * (src/generators/admin-app.ts) from the preset's module manifests — do not edit.
 *
 * 路径为 admin SPA 内部路径（basename /admin 相对路径），与 Sidebar 的
 * NavLink to 一致；manifest 中带 /admin 前缀的路由已归一化。
 * Sidebar 据此隐藏不可用入口，避免点击后渲染空白内容区。
 */
export const AVAILABLE_ADMIN_ROUTES: readonly string[] = [
${lines.join('\n')}
]
`
}

export function generateAdminApp(resolved: ResolvedPreset): string | null {
  if (!resolved.hasAdmin) return null

  const pages = getAdminPages(resolved) ?? []
  if (pages.length === 0) return null

  // Separate public and protected pages
  const publicPages = pages.filter(p => p.isPublic)
  const protectedPages = pages.filter(p => !p.isPublic)

  // Build imports
  const imports = [
    `import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'`,
    `import { ConfigProvider } from 'antd'`,
    `import { Layout } from './layouts/Layout'`,
  ]

  for (const page of pages) {
    imports.push(`import { ${page.name} } from './pages/${page.name}'`)
  }

  // CaptchaModal only if captcha module is included
  const captchaImport = resolved.hasCaptcha ? ', CaptchaModal' : ''
  imports.push(`import { ProtectedRoute${captchaImport} } from './components'`)

  // Route paths must use the basename-relative form: manifest routes may carry
  // a redundant /admin prefix while Sidebar NavLinks use the unprefixed form —
  // emitting the prefixed path made those routes unreachable (blank content
  // area on 分类管理/插件列表/插件审核/插件看板, P2 实测缺陷).
  const protectedRouteElements = protectedPages.map(p => {
    const route = normalizeAdminRoute(p.route)
    return `                    <Route path="${route}" element={<${p.name} />} />`
  })

  const defaultProtectedRoute =
    protectedPages.length > 0 ? normalizeAdminRoute(protectedPages[0].route) : '/'

  const captchaElement = resolved.hasCaptcha ? `\n        <CaptchaModal />` : ''

  const publicRouteLines = publicPages.map(p => {
    const route = normalizeAdminRoute(p.route)
    return `          <Route path="${route}" element={<${p.name} />} />`
  })

  return `${imports.join('\n')}

export const App: React.FC<{ basePath?: string }> = ({ basePath = '/admin' }) => {
  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: '#1890ff',
        },
      }}
    >
      <BrowserRouter basename={basePath}>
        <Routes>
${publicRouteLines.join('\n')}
          <Route
            path="/*"
            element={
              <ProtectedRoute>
                <Layout>
                  <Routes>
                    <Route path="/" element={<Navigate to="${defaultProtectedRoute}" replace />} />
${protectedRouteElements.join('\n')}
                    <Route path="/system/monitor" element={<div className="p-6"><h2 className="text-xl font-semibold">System Monitor</h2><p className="text-gray-500 mt-2">Coming soon...</p></div>} />
                    <Route path="*" element={<div className="flex items-center justify-center h-full min-h-[400px]"><div className="text-center"><h2 className="text-3xl font-semibold mb-2">404</h2><p className="text-gray-500 mt-2">Page not found</p></div></div>} />
                  </Routes>
                </Layout>
              </ProtectedRoute>
            }
          />
        </Routes>${captchaElement}
      </BrowserRouter>
    </ConfigProvider>
  )
}
`
}

/**
 * Generates admin/components/index.ts content based on resolved preset.
 * Conditionally includes CaptchaModal only when captcha module is present.
 */
export function generateAdminComponentsIndex(resolved: ResolvedPreset): string | null {
  if (!resolved.hasAdmin) return null

  const lines = [
    `export { UserTable } from './UserTable'`,
    `export { StatsCard } from './StatsCard'`,
    `export { PageHeader } from './PageHeader'`,
    `export { UserFormModal } from './UserFormModal'`,
    `export { ProtectedRoute } from './ProtectedRoute'`,
  ]

  if (resolved.hasCaptcha) {
    lines.push(`export { CaptchaModal } from './CaptchaModal'`)
  }

  lines.push(`export { PermissionGuard, PermissionButton, Can, Cannot } from './PermissionGuard'`)

  return lines.join('\n') + '\n'
}

/**
 * Generates admin/services/apiClient.ts content based on resolved preset.
 * Conditionally imports captchaStore only when captcha module is present.
 */
export function generateAdminApiClient(resolved: ResolvedPreset): string | null {
  if (!resolved.hasAdmin) return null

  const captchaImport = resolved.hasCaptcha
    ? `import { useCaptchaStore } from '../stores/captchaStore'\n`
    : ''
  const captchaFetchSetup = resolved.hasCaptcha
    ? `  const showCaptcha = useCaptchaStore.getState().show\n\n`
    : ''
  const captchaHandler = resolved.hasCaptcha
    ? `    onShowCaptcha: async config => {
      return showCaptcha({
        type: config.type,
        captchaUrl: config.captchaUrl,
      })
    },`
    : `    onShowCaptcha: async () => true,`

  return `/**
 * @framework-baseline ab16e97716a7556e
 * @framework-modify
 * @reason Conditional captcha support based on preset modules
 * @impact Captcha module excluded = no captchaStore import
 */

import { WSClientImpl } from '@shared/core/ws-client'
import { SSEClientImpl } from '@shared/core/sse-client'
import { createRequestInterceptor } from './requestInterceptor'
${captchaImport}import { createApiFacade } from '@server/rpc-surface'

const baseUrl = import.meta.env.API_BASE_URL || window.location.origin

const TOKEN_KEY = 'admin-storage'

function clearAuthAndRedirect(): void {
  localStorage.removeItem(TOKEN_KEY)
  if (window.location.pathname !== '/admin/login') {
    window.location.href = '/admin/login'
  }
}

function getAuthToken(): string | null {
  try {
    const stored = localStorage.getItem(TOKEN_KEY)
    if (stored) {
      const parsed = JSON.parse(stored)
      return parsed.state?.token || null
    }
  } catch {
    return null
  }
  return null
}

function createCustomFetch() {
${captchaFetchSetup}  return createRequestInterceptor({
    onShowLogin: clearAuthAndRedirect,
${captchaHandler}  })
}

export const apiClient = createApiFacade(baseUrl, {
  fetch: createCustomFetch() as typeof fetch,
  webSocket: url => new WSClientImpl(url) as unknown as WebSocket,
  sse: url => {
    const token = getAuthToken()
    const headers: Record<string, string> = {}
    if (token) {
      headers['Authorization'] = \`Bearer \${token}\`
    }
    return new SSEClientImpl(url, headers)
  },
})

export { api } from '@shared/core/api-request'
`
}
