import {
  plugins,
  pluginVersions,
  pluginCategories,
  pluginCategoryMappings,
} from '@server/db/schema'
import { generateUUID } from '@server/utils/uuid'
import { getDb } from '@server/db'

export async function seedPluginsIfEmpty() {
  const db = await getDb()

  let existing
  try {
    existing = await db.select().from(plugins)
  } catch {
    // Table doesn't exist yet — migrations may not include plugin tables
    return
  }
  if (existing.length > 0) return

  const sampleCategories = [
    {
      id: generateUUID(),
      name: 'UI & Design',
      slug: 'ui-design',
      description: 'Visual customization and theming',
      icon: 'palette',
      sortOrder: 1,
    },
    {
      id: generateUUID(),
      name: 'Analytics',
      slug: 'analytics',
      description: 'Data tracking and reporting',
      icon: 'chart',
      sortOrder: 2,
    },
    {
      id: generateUUID(),
      name: 'SEO & Marketing',
      slug: 'seo-marketing',
      description: 'Search optimization and growth tools',
      icon: 'trending-up',
      sortOrder: 3,
    },
    {
      id: generateUUID(),
      name: 'Developer Tools',
      slug: 'developer-tools',
      description: 'Utilities for developers',
      icon: 'code',
      sortOrder: 4,
    },
    {
      id: generateUUID(),
      name: 'Integration',
      slug: 'integration',
      description: 'Third-party service integrations',
      icon: 'plug',
      sortOrder: 5,
    },
  ]

  await db.insert(pluginCategories).values(sampleCategories)

  const samplePlugins = [
    {
      id: generateUUID(),
      name: 'Theme Engine',
      slug: 'theme-engine',
      description:
        'Advanced theming system with dark mode, custom color palettes, and responsive layout controls.',
      readme:
        '# Theme Engine\n\nA powerful theming plugin for customizing the look and feel of your application.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/theme-engine',
      homepageUrl: 'https://theme-engine.example.com',
      license: 'MIT',
      version: '2.1.0',
      status: 'approved' as const,
      downloadCount: 1520,
      viewCount: 4320,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/theme/800/400',
      tags: '["theme","dark-mode","customization"]',
    },
    {
      id: generateUUID(),
      slug: 'analytics-dashboard',
      name: 'Analytics Dashboard',
      description:
        'Real-time analytics dashboard with charts, heatmaps, and user behavior tracking.',
      readme: '# Analytics Dashboard\n\nTrack user engagement and visualize data in real time.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/analytics-dashboard',
      homepageUrl: 'https://analytics.example.com',
      license: 'Apache-2.0',
      version: '1.5.3',
      status: 'approved' as const,
      downloadCount: 980,
      viewCount: 2100,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/analytics/800/400',
      tags: '["analytics","dashboard","charts"]',
    },
    {
      id: generateUUID(),
      slug: 'seo-optimizer',
      name: 'SEO Optimizer',
      description:
        'Automated SEO optimization with meta tags, sitemap generation, and structured data support.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/seo-optimizer',
      license: 'MIT',
      version: '1.2.0',
      status: 'approved' as const,
      downloadCount: 740,
      viewCount: 1800,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/seo/800/400',
      tags: '["seo","meta","sitemap"]',
    },
    {
      id: generateUUID(),
      slug: 'api-toolkit',
      name: 'API Toolkit',
      description:
        'Developer toolkit for building and testing REST APIs with auto-documentation and mock servers.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/api-toolkit',
      homepageUrl: 'https://api-toolkit.example.com',
      license: 'MIT',
      version: '3.0.1',
      status: 'approved' as const,
      downloadCount: 2100,
      viewCount: 5600,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/apitoolkit/800/400',
      tags: '["api","developer","testing","documentation"]',
    },
    {
      id: generateUUID(),
      slug: 'notification-hub',
      name: 'Notification Hub',
      description:
        'Unified notification management supporting email, SMS, push, and in-app notifications.',
      authorId: '3',
      authorName: 'user1',
      repositoryUrl: 'https://github.com/example/notification-hub',
      license: 'ISC',
      version: '1.0.0',
      status: 'pending' as const,
      downloadCount: 0,
      viewCount: 50,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/notify/800/400',
      tags: '["notification","email","push"]',
    },
    {
      id: generateUUID(),
      slug: 'form-builder',
      name: 'Form Builder',
      description:
        'Drag-and-drop form creation with validation rules, conditional logic, and file uploads.',
      readme:
        '# Form Builder\n\nCreate complex forms with ease using our visual drag-and-drop builder.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/form-builder',
      homepageUrl: 'https://form-builder.example.com',
      license: 'MIT',
      version: '3.2.1',
      status: 'approved' as const,
      downloadCount: 3420,
      viewCount: 8900,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/formbuilder/800/400',
      tags: '["forms","validation","drag-drop"]',
    },
    {
      id: generateUUID(),
      slug: 'image-optimizer',
      name: 'Image Optimizer',
      description:
        'Automatic image compression and format conversion with lazy loading and responsive srcset support.',
      readme: '# Image Optimizer\n\nOptimize images automatically for faster page loads.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/image-optimizer',
      license: 'MIT',
      version: '2.0.0',
      status: 'approved' as const,
      downloadCount: 2890,
      viewCount: 6500,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/imgopt/800/400',
      tags: '["image","optimization","performance"]',
    },
    {
      id: generateUUID(),
      slug: 'cache-manager',
      name: 'Cache Manager',
      description:
        'Redis-powered caching layer with TTL management, cache invalidation, and tag-based purging.',
      readme: '# Cache Manager\n\nSmart caching for high-performance applications.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/cache-manager',
      homepageUrl: 'https://cache-manager.example.com',
      license: 'Apache-2.0',
      version: '1.8.0',
      status: 'approved' as const,
      downloadCount: 1560,
      viewCount: 4200,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/cache/800/400',
      tags: '["cache","redis","performance"]',
    },
    {
      id: generateUUID(),
      slug: 'auth-guard',
      name: 'Auth Guard',
      description:
        'Advanced authentication flows with OAuth2, SAML, and biometric support including session management.',
      readme: '# Auth Guard\n\nEnterprise-grade authentication for modern apps.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/auth-guard',
      homepageUrl: 'https://auth-guard.example.com',
      license: 'MIT',
      version: '4.1.0',
      status: 'approved' as const,
      downloadCount: 4210,
      viewCount: 9800,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/authguard/800/400',
      tags: '["auth","oauth","security"]',
    },
    {
      id: generateUUID(),
      slug: 'payment-gateway',
      name: 'Payment Gateway',
      description:
        'Stripe and PayPal integration with subscription management, invoicing, and refund handling.',
      readme: '# Payment Gateway\n\nAccept payments globally with multiple providers.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/payment-gateway',
      homepageUrl: 'https://payment-gateway.example.com',
      license: 'MIT',
      version: '2.3.0',
      status: 'approved' as const,
      downloadCount: 3100,
      viewCount: 7800,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/payment/800/400',
      tags: '["payment","stripe","subscription"]',
    },
    {
      id: generateUUID(),
      slug: 'chat-widget',
      name: 'Chat Widget',
      description:
        'Real-time customer support chat with AI-powered auto-replies and conversation routing.',
      readme: '# Chat Widget\n\nLive chat support for your customers.',
      authorId: '3',
      authorName: 'user1',
      repositoryUrl: 'https://github.com/example/chat-widget',
      license: 'ISC',
      version: '1.4.2',
      status: 'approved' as const,
      downloadCount: 1870,
      viewCount: 5200,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/chatwidget/800/400',
      tags: '["chat","support","real-time"]',
    },
    {
      id: generateUUID(),
      slug: 'backup-manager',
      name: 'Backup Manager',
      description:
        'Automated database backups with scheduling, encryption, and cloud storage integration.',
      readme: '# Backup Manager\n\nNever lose data with automated backups.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/backup-manager',
      license: 'MIT',
      version: '1.1.0',
      status: 'approved' as const,
      downloadCount: 980,
      viewCount: 2900,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/backup/800/400',
      tags: '["backup","database","scheduling"]',
    },
    {
      id: generateUUID(),
      slug: 'rate-limiter',
      name: 'Rate Limiter',
      description:
        'API rate limiting middleware with sliding window, token bucket, and fixed window algorithms.',
      readme: '# Rate Limiter\n\nProtect your APIs from abuse.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/rate-limiter',
      homepageUrl: 'https://rate-limiter.example.com',
      license: 'MIT',
      version: '2.0.0',
      status: 'approved' as const,
      downloadCount: 1340,
      viewCount: 3800,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/ratelimit/800/400',
      tags: '["rate-limit","api","middleware"]',
    },
    {
      id: generateUUID(),
      slug: 'email-templates',
      name: 'Email Templates',
      description:
        'Responsive email builder with template variables, preview mode, and SMTP integration.',
      readme: '# Email Templates\n\nBeautiful emails that work everywhere.',
      authorId: '3',
      authorName: 'user1',
      repositoryUrl: 'https://github.com/example/email-templates',
      license: 'Apache-2.0',
      version: '1.6.0',
      status: 'approved' as const,
      downloadCount: 2100,
      viewCount: 5600,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/emailtpl/800/400',
      tags: '["email","templates","smtp"]',
    },
    {
      id: generateUUID(),
      slug: 'search-engine',
      name: 'Search Engine',
      description:
        'Elasticsearch integration with faceted search, autocomplete, and relevance tuning.',
      readme: '# Search Engine\n\nPowerful full-text search for your application.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/search-engine',
      homepageUrl: 'https://search-engine.example.com',
      license: 'MIT',
      version: '3.0.0',
      status: 'approved' as const,
      downloadCount: 2560,
      viewCount: 7100,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/searcheng/800/400',
      tags: '["search","elasticsearch","full-text"]',
    },
    {
      id: generateUUID(),
      slug: 'cdn-manager',
      name: 'CDN Manager',
      description:
        'Content delivery network controls with cache purging, URL signing, and geo-routing.',
      readme: '# CDN Manager\n\nDeliver content faster globally.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/cdn-manager',
      license: 'MIT',
      version: '1.3.0',
      status: 'approved' as const,
      downloadCount: 870,
      viewCount: 2400,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/cdn/800/400',
      tags: '["cdn","caching","delivery"]',
    },
    {
      id: generateUUID(),
      slug: 'logger-pro',
      name: 'Logger Pro',
      description:
        'Structured logging with severity levels, log rotation, and remote aggregation support.',
      readme: '# Logger Pro\n\nEnterprise logging made simple.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/logger-pro',
      license: 'BSD-3-Clause',
      version: '2.1.0',
      status: 'approved' as const,
      downloadCount: 1190,
      viewCount: 3300,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/logger/800/400',
      tags: '["logging","monitoring","structured"]',
    },
    {
      id: generateUUID(),
      slug: 'task-scheduler',
      name: 'Task Scheduler',
      description:
        'Cron job management with retry policies, concurrency controls, and execution history.',
      readme: '# Task Scheduler\n\nAutomate recurring tasks with confidence.',
      authorId: '3',
      authorName: 'user1',
      repositoryUrl: 'https://github.com/example/task-scheduler',
      homepageUrl: 'https://task-scheduler.example.com',
      license: 'MIT',
      version: '1.5.0',
      status: 'approved' as const,
      downloadCount: 1780,
      viewCount: 4900,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/tasksched/800/400',
      tags: '["scheduler","cron","automation"]',
    },
    {
      id: generateUUID(),
      slug: 'ab-testing',
      name: 'A/B Testing',
      description:
        'Experiment framework with statistical significance calculation and variant allocation.',
      readme: '# A/B Testing\n\nData-driven decisions through controlled experiments.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/ab-testing',
      license: 'Apache-2.0',
      version: '1.0.0',
      status: 'approved' as const,
      downloadCount: 640,
      viewCount: 2100,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/abtest/800/400',
      tags: '["testing","experiment","analytics"]',
    },
    {
      id: generateUUID(),
      slug: 'markdown-editor',
      name: 'Markdown Editor',
      description:
        'Rich text editing with Markdown support, syntax highlighting, and live preview.',
      readme: '# Markdown Editor\n\nWrite beautifully with Markdown.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/markdown-editor',
      homepageUrl: 'https://md-editor.example.com',
      license: 'MIT',
      version: '2.4.0',
      status: 'approved' as const,
      downloadCount: 2950,
      viewCount: 7400,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/mdeditor/800/400',
      tags: '["markdown","editor","rich-text"]',
    },
    {
      id: generateUUID(),
      slug: 'webhook-manager',
      name: 'Webhook Manager',
      description:
        'Outgoing webhook automation with retry logic, payload templating, and delivery tracking.',
      readme: '# Webhook Manager\n\nReliable webhook delivery for your integrations.',
      authorId: '3',
      authorName: 'user1',
      repositoryUrl: 'https://github.com/example/webhook-manager',
      license: 'MIT',
      version: '1.2.0',
      status: 'pending' as const,
      downloadCount: 520,
      viewCount: 1800,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/webhook/800/400',
      tags: '["webhook","automation","integration"]',
    },
    {
      id: generateUUID(),
      slug: 'two-factor-auth',
      name: 'Two-Factor Auth',
      description: '2FA/MFA support with TOTP, SMS OTP, and hardware key authentication methods.',
      readme: '# Two-Factor Auth\n\nAdd an extra layer of security.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/two-factor-auth',
      license: 'MIT',
      version: '1.7.0',
      status: 'approved' as const,
      downloadCount: 2340,
      viewCount: 6100,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/2fa/800/400',
      tags: '["2fa","security","authentication"]',
    },
    {
      id: generateUUID(),
      slug: 'database-browser',
      name: 'Database Browser',
      description:
        'GUI interface for browsing tables, running queries, and visualizing schema relationships.',
      readme: '# Database Browser\n\nExplore your data visually.',
      authorId: '2',
      authorName: 'customerservice',
      repositoryUrl: 'https://github.com/example/database-browser',
      license: 'GPL-3.0',
      version: '1.0.0',
      status: 'pending' as const,
      downloadCount: 340,
      viewCount: 1200,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/dbbrowser/800/400',
      tags: '["database","gui","query"]',
    },
    {
      id: generateUUID(),
      slug: 'performance-monitor',
      name: 'Performance Monitor',
      description:
        'Core Web Vitals tracking with real user monitoring, alerts, and performance budgets.',
      readme: '# Performance Monitor\n\nKeep your app fast and responsive.',
      authorId: '1',
      authorName: 'superadmin',
      repositoryUrl: 'https://github.com/example/performance-monitor',
      homepageUrl: 'https://perf-monitor.example.com',
      license: 'MIT',
      version: '2.0.0',
      status: 'approved' as const,
      downloadCount: 1890,
      viewCount: 5300,
      featured: true,
      screenshotUrl: 'https://picsum.photos/seed/perfmon/800/400',
      tags: '["performance","monitoring","web-vitals"]',
    },
    {
      id: generateUUID(),
      slug: 'i18n-manager',
      name: 'i18n Manager',
      description:
        'Internationalization toolkit with translation memory, pluralization, and RTL support.',
      readme: '# i18n Manager\n\nGo global with multilingual support.',
      authorId: '3',
      authorName: 'user1',
      repositoryUrl: 'https://github.com/example/i18n-manager',
      license: 'MIT',
      version: '1.3.0',
      status: 'approved' as const,
      downloadCount: 1450,
      viewCount: 4100,
      featured: false,
      screenshotUrl: 'https://picsum.photos/seed/i18n/800/400',
      tags: '["i18n","translation","localization"]',
    },
  ]

  await db.insert(plugins).values(samplePlugins)

  const sampleVersions = [
    {
      id: generateUUID(),
      pluginId: samplePlugins[0].id,
      version: '2.1.0',
      changelog: 'Added responsive layout controls',
      status: 'approved' as const,
    },
    {
      id: generateUUID(),
      pluginId: samplePlugins[0].id,
      version: '2.0.0',
      changelog: 'Major rewrite with dark mode support',
      status: 'approved' as const,
    },
    {
      id: generateUUID(),
      pluginId: samplePlugins[1].id,
      version: '1.5.3',
      changelog: 'Fixed heatmap rendering',
      status: 'approved' as const,
    },
    {
      id: generateUUID(),
      pluginId: samplePlugins[1].id,
      version: '1.5.0',
      changelog: 'Added real-time tracking',
      status: 'approved' as const,
    },
    {
      id: generateUUID(),
      pluginId: samplePlugins[2].id,
      version: '1.2.0',
      changelog: 'Structured data support',
      status: 'approved' as const,
    },
    {
      id: generateUUID(),
      pluginId: samplePlugins[3].id,
      version: '3.0.1',
      changelog: 'Auto-documentation improvements',
      status: 'approved' as const,
    },
    {
      id: generateUUID(),
      pluginId: samplePlugins[3].id,
      version: '3.0.0',
      changelog: 'Major version with mock server',
      status: 'approved' as const,
    },
    {
      id: generateUUID(),
      pluginId: samplePlugins[4].id,
      version: '1.0.0',
      changelog: 'Initial release',
      status: 'pending' as const,
    },
  ]

  await db.insert(pluginVersions).values(sampleVersions)

  const sampleMappings = [
    { pluginId: samplePlugins[0].id, categoryId: sampleCategories[0].id },
    { pluginId: samplePlugins[1].id, categoryId: sampleCategories[1].id },
    { pluginId: samplePlugins[2].id, categoryId: sampleCategories[2].id },
    { pluginId: samplePlugins[3].id, categoryId: sampleCategories[3].id },
    { pluginId: samplePlugins[4].id, categoryId: sampleCategories[4].id },
  ]

  await db.insert(pluginCategoryMappings).values(sampleMappings)

  // Plugin seeding complete
}
