// 自动生成：npx tsx scripts/generate-test-playbooks.ts
export const PLAYBOOKS = [
  {
    portalId: 'fullstack',
    zh: '全模块管理后台',
    name: 'Fullstack Admin',
    site: 'https://fullstack.lpm1.top',
    identity: '超级管理员',
    pos: 14,
    neg: 8,
    cases: [
      {
        t: '登录管理后台',
        s: [
          '打开 https://fullstack.lpm1.top/admin',
          '在用户名输入框输入 superadmin',
          '在密码输入框输入 123456',
          '点击登录按钮',
        ],
        v: 'SPA 跳转到 /admin/dashboard，侧栏 10 项且 href 全带 /admin 前缀',
        shot: 'verify/verify-admin-login.png',
        neg: false,
      },
      {
        t: '查看仪表盘统计',
        s: ['登录后自动到达 /admin/dashboard'],
        v: '统计卡显示 总待办12/待处理4/已完成5',
        shot: 'verify/verify-admin-dashboard.png',
        neg: false,
      },
      {
        t: '用户管理（查看/创建/编辑/删除）',
        s: ['点击侧栏"用户与订单" → "用户管理"', '或直接访问 /admin/users'],
        v: '表格 3 行（superadmin/customerservice/user1），角色徽章+状态正常',
        shot: 'matrix/fullstack/super-admin/fa-admin-users.png',
        neg: false,
      },
      {
        t: '内容管理（新建/编辑/发布）',
        s: ['点击侧栏"内容管理" → "内容列表"'],
        v: '2 篇已发布文章可见，编辑操作可用',
        shot: 'matrix/fullstack/super-admin/fa-admin-content.png',
        neg: false,
      },
      {
        t: '角色与权限管理',
        s: ['点击侧栏"系统管理" → "角色权限"'],
        v: '3 角色列表（super_admin/customer_service/user），权限矩阵完整',
        shot: 'matrix/fullstack/super-admin/fa-admin-roles.png',
        neg: false,
      },
      {
        t: '系统设置读写',
        s: ['点击侧栏"系统管理" → "系统设置"'],
        v: '表单带出真实值（站点名称/SMTP/通知/安全四个分区）',
        shot: 'matrix/fullstack/super-admin/fa-admin-settings.png',
        neg: false,
      },
      {
        t: '审计日志查看',
        s: ['点击侧栏"系统管理" → "系统日志"'],
        v: '20+ 行审计日志（时间/用户ID/IP/详情）',
        shot: 'matrix/fullstack/super-admin/fa-admin-logs.png',
        neg: false,
      },
      {
        t: '验证码限流触发（逆向防御验证）',
        s: ['打开 /admin/test/captcha 验证码测试页', '点击"连续请求 20 次"'],
        v: '真实弹出验证码 Modal；输入正确码提交后弹窗关闭（响应链闭环）',
        shot: null,
        neg: true,
      },
      {
        t: '空标题内容创建被拒（逆向）',
        s: ['内容管理 → 新建内容', '不填标题直接提交'],
        v: '表单/zod 校验拦截并提示必填，不产生脏数据',
        shot: null,
        neg: true,
      },
      {
        t: '未登录访问管理 API（逆向）',
        s: ['不带 Authorization 请求 /api/admin/stats'],
        v: '返回 401，不泄露任何统计',
        shot: null,
        neg: true,
      },
      {
        t: '内容编辑后改回原样（正向链）',
        s: [
          '内容管理 → 内容列表，点击行内"编辑"按钮',
          '修改标题后点击 OK 保存',
          '再次编辑同一行，改回原标题后 OK 保存',
        ],
        v: '表格标题先更新后恢复原值，状态保持已发布，无多余行',
        shot: 'matrix/fullstack/super-admin/fa-admin-content.png',
        neg: false,
      },
      {
        t: '系统设置修改后还原（正向链）',
        s: [
          '系统管理 → 系统设置，修改站点名称为 QA-Temp-Name',
          '点击"保存更改"',
          '改回原值 Biomimic Admin 再次保存',
        ],
        v: '两次均出现"设置保存成功!" toast，GET /api/admin/settings 回读 siteName 为原值',
        shot: 'matrix/fullstack/super-admin/fa-admin-settings.png',
        neg: false,
      },
      {
        t: '仪表盘刷新后统计保持（正向）',
        s: ['登录到达 /admin/dashboard 记录统计卡数值', '按 F5 硬刷新'],
        v: '刷新后统计卡与刷新前一致（GET /api/admin/stats 200），无清零',
        shot: 'verify/verify-admin-dashboard.png',
        neg: false,
      },
      {
        t: '订单/工单/纠纷空数据页巡检（正向边界）',
        s: ['依次访问 /admin/orders、/admin/tickets、/admin/disputes'],
        v: '三页壳与表格头渲染正常，统计卡全 0 + No data（线上无 mock 数据），无报错',
        shot: 'matrix/fullstack/super-admin/fa-admin-orders.png',
        neg: false,
      },
      {
        t: '分类管理与权限页深链（边界实勘）',
        s: ['直接打开 /admin/categories', '再直接打开 /admin/permissions'],
        v: '实勘：categories 超管侧渲染情况未采样（API /api/categories 200 有数据）；permissions 深链 200 但内容区空白（已知缺陷）——逐页记录',
        shot: 'matrix/fullstack/super-admin/fa-admin-categories.png',
        neg: false,
      },
      {
        t: 'emoji/中英混合标题正常创建（正向）',
        s: [
          '内容列表点击"创建内容"',
          '标题输入 🎉 Release Notes 发布v2 中英混合，填写其余必填项提交',
          '确认后删除该条清理',
        ],
        v: '列表正常渲染该条无乱码无报错，清理后列表恢复基线',
        shot: null,
        neg: false,
      },
      {
        t: '连续创建 3 条内容（正向批量链）',
        s: ['连续点击"创建内容"新建 3 条不同标题的内容并逐一提交', '记录列表新增数量'],
        v: '3 条均出现在列表，随后全部删除清理，列表回到基线',
        shot: null,
        neg: false,
      },
      {
        t: '超长标题提交（逆向）',
        s: ['点击"创建内容"', '标题粘贴 256+ 字符长串，提交'],
        v: '实勘：被长度校验拒绝则提示报错；若接受则正常入库显示——记录行为，前端不崩溃',
        shot: null,
        neg: true,
      },
      {
        t: '纯空格标题提交被拒（逆向）',
        s: ['点击"创建内容"', '标题只输入多个空格，提交'],
        v: '校验拦截（trim 后按必填处理），不产生空标题脏数据',
        shot: null,
        neg: true,
      },
      {
        t: 'XSS 注入标题转义验证（逆向）',
        s: ['点击"创建内容"', '标题输入 <script>alert(1)<\/script>，提交', '回到列表查看该条渲染'],
        v: '标题按纯文本渲染不执行（无弹窗），列表与详情均无脚本注入效果',
        shot: null,
        neg: true,
      },
      {
        t: '伪造 Bearer token 调管理 API（逆向）',
        s: ['curl -H "Authorization: Bearer fake-token123" 请求 /api/admin/stats'],
        v: '返回 401，伪造 token 不被接受（仅预置 mock token 可用）',
        shot: null,
        neg: true,
      },
      {
        t: '双击创建内容提交防重（逆向）',
        s: ['填写完整创建表单后快速双击 OK 提交按钮'],
        v: '实勘：仅创建 1 条（若出现重复行记录为缺陷），随后清理',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'fullstack',
    zh: '全模块管理后台',
    name: 'Fullstack Admin',
    site: 'https://fullstack.lpm1.top',
    identity: '客服人员',
    pos: 4,
    neg: 4,
    cases: [
      {
        t: '登录（快捷按钮）',
        s: ['打开 /admin', '点击"客服人员"快捷登录按钮'],
        v: '登录成功，header 显示 customerservice + 客服人员徽标',
        shot: 'matrix/fullstack/cs-01-dashboard.png',
        neg: false,
      },
      {
        t: '仪表盘统计被拒（API 403 → 卡片显示 0）',
        s: ['登录后到达 /admin/dashboard'],
        v: '统计卡全 0（API 403），但页面壳正常渲染',
        shot: 'matrix/fullstack/cs-01-dashboard.png',
        neg: true,
      },
      {
        t: '用户管理数据被拒（API 403 → 空表）',
        s: ['点击侧栏"用户管理"'],
        v: '表头完整但 No data（API 403）',
        shot: 'matrix/fullstack/cs-03-users-page-denied-empty.png',
        neg: true,
      },
      {
        t: '内容列表可见（只读）',
        s: ['点击侧栏"内容管理" → "内容列表"'],
        v: '2 篇文章可见，无编辑/删除按钮，无新建按钮',
        shot: 'matrix/fullstack/cs-02-notification-center-empty.png',
        neg: false,
      },
      {
        t: '客服登出（正向链）',
        s: ['登录后点击 header 头像下拉', '点击"退出登录"'],
        v: '跳回 /admin/login，重新进入后台需再次登录（customer-service-token 登出）',
        shot: null,
        neg: false,
      },
      {
        t: '客服刷新后只读权限保持（正向）',
        s: ['进入 /admin/content 后按 F5 硬刷新'],
        v: '刷新后仍无"创建内容"按钮、行内无编辑按钮（只读态持久）',
        shot: 'matrix/fullstack/cs-full/cs-full-02-content-readonly-with-data.png',
        neg: false,
      },
      {
        t: '客服伪造角色提权（逆向）',
        s: [
          'localStorage 把 admin-storage 的 user.role 改为 super_admin',
          '刷新后请求 /api/admin/users',
        ],
        v: '后端按 token 鉴权仍 403 Permission denied，前端角色字段篡改不提权',
        shot: null,
        neg: true,
      },
      {
        t: '客服保存系统设置被拦截（逆向）',
        s: ['进入系统设置（表单空，GET 403）', '点击"保存更改"'],
        v: '保存被拦截（验证码/403），无任何配置变更落库',
        shot: 'matrix/fullstack/cs-05-settings-save-blocked-by-captcha.png',
        neg: true,
      },
    ],
  },
  {
    portalId: 'fullstack',
    zh: '全模块管理后台',
    name: 'Fullstack Admin',
    site: 'https://fullstack.lpm1.top',
    identity: '普通用户',
    pos: 2,
    neg: 4,
    cases: [
      {
        t: '登录（快捷按钮）',
        s: ['打开 /admin', '点击"普通用户"快捷登录按钮'],
        v: '登录成功，header 显示 user1 + 普通用户徽标',
        shot: 'matrix/fullstack/user-01-dashboard.png',
        neg: false,
      },
      {
        t: '仪表盘统计被拒',
        s: ['登录后到达 /admin/dashboard'],
        v: '统计卡全 0（API 403）',
        shot: 'matrix/fullstack/user-01-dashboard.png',
        neg: true,
      },
      {
        t: '用户管理数据被拒',
        s: ['点击侧栏"用户管理"'],
        v: '表头完整但 No data',
        shot: 'matrix/fullstack/user-03-users-page-denied-empty.png',
        neg: true,
      },
      {
        t: '普通用户登出（正向链）',
        s: ['登录后打开头像下拉', '点击"退出登录"'],
        v: '跳回 /admin/login，user-token 登出',
        shot: null,
        neg: false,
      },
      {
        t: '普通用户 token 直调管理 API（逆向）',
        s: ['curl -H "Authorization: Bearer user-token" 请求 /api/admin/stats 与 /api/admin/users'],
        v: '均 403 Permission denied，与 UI 空数据一致（token 合法但无权限）',
        shot: null,
        neg: true,
      },
      {
        t: '角色切换下拉提权链（逆向·已知缺陷复现）',
        s: ['登录后点击 header 角色切换下拉', '选择"超级管理员"'],
        v: '⚠ 已知缺陷：admin-storage 的 user+token 被整体替换为目标角色（提权链）；记录切换后可访问的页面与 API，不作为通过标准',
        shot: 'matrix/fullstack/user-05-role-switcher-dropdown.png',
        neg: true,
      },
    ],
  },
  {
    portalId: 'fullstack',
    zh: '全模块管理后台',
    name: 'Fullstack Admin',
    site: 'https://fullstack.lpm1.top',
    identity: '游客（未登录）',
    pos: 2,
    neg: 4,
    cases: [
      {
        t: '浏览 /todos 页（SSR 渲染数据）',
        s: ['直接打开 https://fullstack.lpm1.top/todos（不登录）'],
        v: 'Todo List 页渲染 + SSR 数据可见',
        shot: 'verify/verify-todos.png',
        neg: false,
      },
      {
        t: '写操作被拒（API 401）',
        s: ['在 /todos 页尝试新增（需登录态）'],
        v: '游客自动登录（dev token），无需手动认证',
        shot: null,
        neg: true,
      },
      {
        t: '访问 /admin 被重定向',
        s: ['直接打开 https://fullstack.lpm1.top/admin'],
        v: '302 → /admin/login 登录页',
        shot: 'verify/verify-admin-login.png',
        neg: false,
      },
      {
        t: '游客刷新 /todos 后 SSR 数据保持（正向）',
        s: ['打开 /todos 记录渲染内容', '按 F5 硬刷新'],
        v: '刷新后 Todo List 与 SSR 数据仍完整渲染（window.__SSR_DATA__.todos），无空白',
        shot: 'verify/verify-todos.png',
        neg: true,
      },
      {
        t: '伪造 token 调 todos 写接口（逆向）',
        s: ['curl -X POST -H "Authorization: Bearer fake-token123" 请求 /api/todos'],
        v: '返回 401，不产生任何待办数据',
        shot: null,
        neg: true,
      },
      {
        t: '游客深链 /admin/users 被拦（逆向）',
        s: ['未登录直接打开 https://fullstack.lpm1.top/admin/users'],
        v: '302 重定向到 /admin/login，不渲染任何用户数据',
        shot: 'verify/verify-admin-login.png',
        neg: true,
      },
    ],
  },
  {
    portalId: 'saas',
    zh: '多租户 SaaS',
    name: 'SaaS Multi-Tenant',
    site: 'https://saas.lpm1.top',
    identity: '租户管理员',
    pos: 17,
    neg: 8,
    cases: [
      {
        t: '登录租户控制台',
        s: [
          '打开 https://saas.lpm1.top/tenant/login',
          '输入 superadmin / admin123',
          '点击 Sign in',
        ],
        v: '进入 /tenant/dashboard，四统计卡正常',
        shot: 'journeys/saas-j1-login.png',
        neg: false,
      },
      {
        t: '查看仪表盘',
        s: ['登录后自动到达 /tenant/dashboard'],
        v: 'Total Users / Active Todos / Content Items / Monthly Revenue 统计卡',
        shot: 'journeys/saas-j2-dashboard.png',
        neg: false,
      },
      {
        t: '成员列表管理',
        s: ['点击侧栏 Users'],
        v: '成员表格 + 角色徽章 + Invite member 按钮',
        shot: 'journeys/saas-j3-members.png',
        neg: false,
      },
      {
        t: '邀请成员（正向→正向链）',
        s: [
          '点击 Invite member',
          '填写邮箱 member@example.com',
          '选择角色（下拉）',
          '点击 Send invitation',
        ],
        v: '绿色 toast "Invitation created"',
        shot: 'journeys/saas-j5-invite-done.png',
        neg: false,
      },
      {
        t: '租户设置',
        s: ['点击侧栏 Settings', '修改 Tenant Name', '点击保存'],
        v: 'toast "Settings updated successfully"',
        shot: 'matrix/saas/tadmin/a-05-settings.png',
        neg: false,
      },
      {
        t: '超管工作台全景（2026-09-12 补拍）',
        s: ['superadmin/admin123 登录 /tenant/login'],
        v: '四统计卡正常；P3：Total Users=1 与成员视角=4 矛盾',
        shot: 'matrix/saas/tadmin/t-11-dashboard.png',
        neg: false,
      },
      {
        t: '租户列表页（逆向：UI 缺失）',
        s: ['探测 /tenant/tenants 与 /admin'],
        v: '⚠ P2：无租户列表页（回退控制台壳），但 GET /api/tenants 200 数据在',
        shot: 'matrix/saas/tadmin/t-12-tenants-list-missing.png',
        neg: true,
      },
      {
        t: '成员管理表（超管视角）',
        s: ['访问 /tenant/users'],
        v: 'Members 表 4 行 + Role/Remove + Invite；已知 P3：Joined=Invalid Date',
        shot: 'matrix/saas/tadmin/t-13-tenant-members.png',
        neg: false,
      },
      {
        t: '审计日志页（逆向：无 UI 无租户维度）',
        s: ['探测 /tenant/audit /tenant/audit-logs /tenant/logs'],
        v: '⚠ P2：三路由全回退壳无内容；API 仅全局 /api/audit-logs 可达',
        shot: 'matrix/saas/tadmin/t-14-audit-logs-missing.png',
        neg: true,
      },
      {
        t: '平台租户列表查看',
        s: ['超管登录后侧栏点击"平台租户"（/tenant/tenants）'],
        v: '租户表格渲染全部租户（名称/套餐/状态 Tag）',
        shot: 'matrix/saas/tadmin/t-12-tenants-list-missing.png',
        neg: false,
      },
      {
        t: '平台审计日志查看',
        s: ['侧栏点击"审计日志"（/tenant/audit）'],
        v: '审计表格渲染（时间/用户/操作/资源/IP），分页可用',
        shot: 'matrix/saas/tadmin/t-14-audit-logs-missing.png',
        neg: false,
      },
      {
        t: '邀请无效邮箱被拒（逆向）',
        s: ['Invite member 填入非法格式邮箱提交'],
        v: '表单/后端校验拦截，提示格式错误，不产生邀请',
        shot: null,
        neg: true,
      },
      {
        t: '租户设置修改后还原（正向链）',
        s: [
          'Settings 页把 Tenant Name 改为 QA-Temp-Name',
          '点击 Save Settings',
          '改回 Saas Demo 再次保存',
        ],
        v: '两次均 toast "Settings updated successfully"，回读 #name 为 Saas Demo',
        shot: 'matrix/saas/tadmin/a-05-settings.png',
        neg: false,
      },
      {
        t: '仪表盘刷新后统计保持（正向）',
        s: ['登录后记录 /tenant/dashboard 四统计卡数值', '按 F5 硬刷新'],
        v: '刷新后四统计卡与刷新前一致（已知口径矛盾另案），无清零',
        shot: 'journeys/saas-j2-dashboard.png',
        neg: false,
      },
      {
        t: '平台租户列表渲染与分页探测（正向实勘）',
        s: ['侧栏点击"平台租户"进入 /tenant/tenants', '检查表格行数、排序与分页控件'],
        v: '实勘：9 个租户渲染（ID 1..11），分页/排序能力以实勘为准——操作后表格无崩溃',
        shot: 'matrix/saas/tadmin/t-12-tenants-list-missing.png',
        neg: false,
      },
      {
        t: '审计日志列表与排序探测（正向实勘）',
        s: ['侧栏点击"审计日志"进入 /tenant/audit', '检查 20 行渲染与操作 tag'],
        v: '实勘：表格 20 行 + create tag 渲染；排序/分页能力记录，操作后无崩溃',
        shot: 'matrix/saas/tadmin/t-14-audit-logs-missing.png',
        neg: false,
      },
      {
        t: '邀请角色选普通成员（正向链）',
        s: [
          'Users 页点击 Invite member',
          '填入 invite-member-qa@demo.io',
          '角色下拉选"普通成员"',
          '点击 Send invitation',
        ],
        v: '绿色 toast "Invitation created"，角色为 tr_saas_member',
        shot: 'matrix/saas/tadmin/a-03a-invite-modal-role-dropdown.png',
        neg: false,
      },
      {
        t: 'Todo 连续创建 3 条（正向批量链）',
        s: ['进入 /tenant/todos', '连续 + Add Todo 创建 3 条不同标题（OK 提交）'],
        v: '3 条均出现在管理员列表（管理员可见全部创建者行），随后逐条删除清理',
        shot: 'matrix/saas/tadmin/a-06-todos.png',
        neg: false,
      },
      {
        t: 'Todo 创建后删除闭环（正向）',
        s: ['+ Add Todo 创建一条 qa-delete-me', '行内点击删除按钮', 'Confirm Delete 弹窗点击 Yes'],
        v: '确认后该行移除，列表计数回落',
        shot: 'matrix/saas/tadmin/a-06-todos.png',
        neg: false,
      },
      {
        t: '超管登出重登（正向链）',
        s: ['header 用户图标 → Logout', '重新 superadmin/admin123 登录'],
        v: '登出跳 /tenant/login 且 tenant-token/current-tenant-slug 双清空，重登后 dashboard 正常',
        shot: 'journeys/saas-j1-login.png',
        neg: false,
      },
      {
        t: '邀请超长邮箱被拒（逆向）',
        s: ['Invite member 邮箱填入 256+ 字符非法长串', '点击 Send invitation'],
        v: '表单/后端校验拦截（格式或长度），不产生邀请记录',
        shot: null,
        neg: true,
      },
      {
        t: '邀请纯空格邮箱被拒（逆向）',
        s: ['Invite member 邮箱只输入空格', '点击 Send invitation'],
        v: '校验拦截提示格式错误，不产生邀请',
        shot: null,
        neg: true,
      },
      {
        t: 'Todo 标题 XSS 注入转义验证（逆向）',
        s: ['+ Add Todo 标题输入 <script>alert(1)<\/script>', 'OK 提交后查看列表'],
        v: '标题纯文本渲染不执行（无弹窗），随后删除清理',
        shot: null,
        neg: true,
      },
      {
        t: '伪造 Bearer token 调平台 API（逆向）',
        s: ['curl -H "Authorization: Bearer fake-token123" 请求 GET /api/tenants'],
        v: '返回 401，不泄露租户清单',
        shot: null,
        neg: true,
      },
      {
        t: '双击 Send invitation 防重（逆向）',
        s: ['填写邀请表单后快速双击 Send invitation'],
        v: '实勘：仅 1 次 toast/1 条邀请（若重复创建记录为缺陷），随后清理',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'saas',
    zh: '多租户 SaaS',
    name: 'SaaS Multi-Tenant',
    site: 'https://saas.lpm1.top',
    identity: '租户成员',
    pos: 7,
    neg: 7,
    cases: [
      {
        t: '接受邀请加入租户',
        s: [
          '注册新账号（POST /api/auth/register）',
          '超管创建邀请并获取 token',
          '登录后打开 /tenant/invite/<token>',
          '点击 Accept invitation',
        ],
        v: '自动进入 /tenant/dashboard',
        shot: 'journeys/saas-j7-accept.png',
        neg: false,
      },
      {
        t: '邀请成员被拒（API 403）',
        s: ['以成员身份登录', '尝试点击 Invite member'],
        v: 'UI 按钮可见但提交后 API 403 Permission denied',
        shot: 'matrix/saas/member/m-02-users.png',
        neg: true,
      },
      {
        t: '成员视角工作台（2026-09-12 补拍）',
        s: ['成员登录 /tenant/login'],
        v: '落地 dashboard，按用户隔离（A Todos=0）；P3：顶栏写死 Tenant Admin',
        shot: 'matrix/saas/member/m-10-workbench.png',
        neg: false,
      },
      {
        t: '成员视角数据页',
        s: ['访问 /tenant/todos'],
        v: 'No data（用户隔离）；⚠ 管理入口 +Add Todo 未按权限隐藏',
        shot: 'matrix/saas/member/m-11-data-todos.png',
        neg: false,
      },
      {
        t: '越权邀请（逆向：前端静默吞 403）',
        s: ['成员提交邀请表单'],
        v: '⚠ P2 BUG：UI 零反馈静默失败（后端 403 正确，前端不提示）',
        shot: 'matrix/saas/member/m-12-permission-denied.png',
        neg: true,
      },
      {
        t: '成员访问租户设置（逆向：越权可写）',
        s: ['成员身份访问 /tenant/settings'],
        v: '⚠ P2 BUG：Tenant Name 可编辑可保存（成员可改租户名）',
        shot: 'matrix/saas/member/m-13-settings.png',
        neg: true,
      },
      {
        t: '成员视角无成员管理按钮（RBAC 收敛验证）',
        s: ['成员身份进入 Users 页'],
        v: '无 Invite member 按钮、成员行无 Role/Remove 操作控件，Role 仅只读徽章',
        shot: null,
        neg: false,
      },
      {
        t: '成员越权访问平台 API（逆向）',
        s: ['成员 token 直接请求 GET /api/tenants 与 /api/audit-logs'],
        v: '均返回 403，不泄露平台级数据',
        shot: null,
        neg: true,
      },
      {
        t: '成员新增 Todo（正向）',
        s: ['成员登录进入 /tenant/todos', '+ Add Todo 填写标题提交'],
        v: 'todo 创建成功且仅自己可见（成员视角 data:create 权限）',
        shot: 'matrix/saas/member/m-05-todos.png',
        neg: false,
      },
      {
        t: '成员删除自己 Todo（正向闭环）',
        s: ['在刚创建的 todo 行点击删除', '确认弹窗点击 Yes'],
        v: '该行移除回到基线，成员数据隔离不波及他人',
        shot: null,
        neg: false,
      },
      {
        t: '成员登出重登状态保持（正向链）',
        s: ['header 用户图标 → Logout', '重新以 member-matrix 登录'],
        v: '重登后仍落地 /tenant/dashboard，数据隔离（A Todos=0）与角色不变',
        shot: 'matrix/saas/member/m-01-dashboard.png',
        neg: false,
      },
      {
        t: '成员访问平台租户页（逆向·已知缺陷复现）',
        s: ['成员身份硬加载 /tenant/tenants'],
        v: '⚠ 已知缺陷：成员亦渲染全量平台租户表（super_admin 鉴权前后端两层均缺）；记录复现，不作为通过标准',
        shot: null,
        neg: true,
      },
      {
        t: '成员 Todo 超长标题（逆向）',
        s: ['+ Add Todo 标题粘贴 256+ 字符', 'OK 提交'],
        v: '实勘：被 zod 长度校验拒绝则提示；接受则正常入列——记录行为，无崩溃',
        shot: null,
        neg: true,
      },
      {
        t: '缺 roleId 的邀请 API 被拒（逆向·API 级）',
        s: ['以成员 JWT POST /api/tenants/5/members/invite，body 只含 email 不含 roleId'],
        v: '返回 400 ZodError（缺 roleId），不产生邀请；越权邀请 403 另案',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'saas',
    zh: '多租户 SaaS',
    name: 'SaaS Multi-Tenant',
    site: 'https://saas.lpm1.top',
    identity: '访客（未登录）',
    pos: 5,
    neg: 12,
    cases: [
      {
        t: '直访受保护页被拦截',
        s: ['直接打开 /tenant/dashboard（不登录）'],
        v: '被 TenantGuard 拦回 /tenant/login',
        shot: 'journeys/saas-r2-loggedout.png',
        neg: false,
      },
      {
        t: '伪造邀请 token 被拒',
        s: ['打开 /tenant/invite/invalid-token-12345'],
        v: '红字 "Invitation not found."',
        shot: 'journeys/saas-r1-badtoken.png',
        neg: true,
      },
      {
        t: '门户首页全貌（2026-09-12 补拍）',
        s: ['打开 /（未登录）'],
        v: 'SPA 重定向 /todos，落地页完整（导航/Todos/SSE Demo/Sign In+Sign Up）',
        shot: 'matrix/saas/guest/g-03-home-landing.png',
        neg: false,
      },
      {
        t: '直访 /tenant/console 拦截',
        s: ['未登录打开 /tenant/console'],
        v: 'TenantGuard 拦回 /tenant/login 登录卡',
        shot: 'matrix/saas/guest/g-04-console-redirect.png',
        neg: false,
      },
      {
        t: '注册页表单',
        s: ['打开 /register'],
        v: 'Create Account 卡完整；注意 SPA 自动播种 Demo User 怪癖',
        shot: 'matrix/saas/guest/g-05-register.png',
        neg: false,
      },
      {
        t: '忘记密码入口探测（逆向：全线缺失）',
        s: ['/login /register /tenant/login 三页文本探测 forgot/help/reset'],
        v: '⚠ 缺口：全站无忘记密码/帮助入口（SKIP 记录）',
        shot: null,
        neg: true,
      },
      {
        t: '游客首页移动版（375px）',
        s: ['切 375x812 视口打开首页'],
        v: '纵向堆叠正常；⚠ P3：375px 页头隐藏，游客看不到登录入口',
        shot: 'matrix/saas/guest/g-15-home-mobile.png',
        neg: true,
      },
      {
        t: '未登录访问平台 API（逆向）',
        s: ['无 token 请求 GET /api/tenants'],
        v: '返回 401，不泄露租户清单',
        shot: null,
        neg: true,
      },
      {
        t: '错误密码登录被拒（逆向）',
        s: ['/tenant/login 输入 superadmin / wrongpass', '点击 Sign in'],
        v: '登录失败提示错误，不进入 dashboard，不签发有效 token',
        shot: null,
        neg: true,
      },
      {
        t: '纯空格账号登录被拒（逆向）',
        s: ['账号输入空格，密码输入任意值', '点击 Sign in'],
        v: '校验或后端拒绝，停留登录页不进入控制台',
        shot: null,
        neg: true,
      },
      {
        t: 'XSS 注入登录账号（逆向）',
        s: ['账号输入 <script>alert(1)<\/script>，密码任意', '点击 Sign in'],
        v: '错误提示按文本渲染不执行脚本（无弹窗），登录失败',
        shot: null,
        neg: true,
      },
      {
        t: '双击登录按钮防重（逆向）',
        s: ['填入有效凭据后快速双击 Sign in'],
        v: '仅一次登录跳转，不产生双 token/双跳转',
        shot: null,
        neg: true,
      },
      {
        t: '注册必填项逐个缺失（逆向）',
        s: ['打开 /register', '分别只填两项留一项提交（username/email/password 三轮）'],
        v: '每轮均被校验拦截并提示对应必填项，不产生半注册账号',
        shot: 'matrix/saas/guest/g-05-register.png',
        neg: true,
      },
      {
        t: '注册密码短于 6 位被拒（逆向）',
        s: ['/register 填写合法用户名/邮箱，密码输入 abc1', '提交'],
        v: 'min 6 校验拦截并提示，注册不成功',
        shot: null,
        neg: true,
      },
      {
        t: '注册含 emoji 用户名（正向实勘）',
        s: ['/register 用户名输入 🚀qa_emoji 类含 emoji 用户名提交'],
        v: '实勘：注册成功或被校验拒绝均记录（参考 todo 站中文名可用先例），无 500',
        shot: null,
        neg: false,
      },
      {
        t: '访客直访租户子页批量拦截（逆向）',
        s: ['未登录依次直接打开 /tenant/users、/tenant/todos、/tenant/settings'],
        v: '三个路由均被 TenantGuard 拦回 /tenant/login，不泄露任何数据',
        shot: 'matrix/saas/guest/g-04-console-redirect.png',
        neg: true,
      },
      {
        t: '伪造 token 调 /api/auth/me（逆向）',
        s: ['curl -H "Authorization: Bearer fake-token123" 请求 GET /api/auth/me'],
        v: '返回 401，不返回任何身份信息',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'todo',
    zh: '经典全栈',
    name: 'Todo App',
    site: 'https://todo.lpm1.top',
    identity: '注册用户',
    pos: 7,
    neg: 5,
    cases: [
      {
        t: '注册新账号',
        s: ['打开 /register', '填写 Username/Email/Password（min 6）', '点击注册'],
        v: '跳转到 /login，无报错',
        shot: 'matrix/todo/todo-09-register.png',
        neg: false,
      },
      {
        t: 'Todos CRUD 全流程',
        s: [
          '登录后打开 /todos',
          '在输入框填写标题',
          '点击 Add Todo',
          '用状态下拉改为 completed',
          '点击删除按钮',
        ],
        v: '新增→变绿→删除，Total 计数正确变化',
        shot: 'journeys/todo-j2-add.png',
        neg: false,
      },
      {
        t: 'WebSocket 聊天',
        s: ['打开 /websocket', '点击 Connect', '在输入框填写消息', '点击 Send'],
        v: 'Status 变 Open，ECHO REQUEST/RESPONSE 往返',
        shot: 'matrix/todo/09-websocket.png',
        neg: false,
      },
      {
        t: '空标题提交无效（逆向）',
        s: ['打开 /todos', '不输入标题直接点击 Add Todo'],
        v: '提交被拦截，Total 计数不变',
        shot: null,
        neg: true,
      },
      {
        t: 'WebSocket 未连接发消息（逆向）',
        s: ['打开 /websocket', '不点 Connect 直接在输入框发送'],
        v: '提示未连接或消息不发出，无假成功',
        shot: null,
        neg: true,
      },
      {
        t: '连续添加 3 条 todo（正向批量链）',
        s: ['打开 /todos', '连续 3 次输入不同标题并点击 Add Todo'],
        v: 'Total +3，三条按提交顺序置顶，输入框逐次清空',
        shot: 'journeys/todo-j2-add.png',
        neg: false,
      },
      {
        t: '筛选切换组合（正向）',
        s: ['/todos 依次点击 filter-pending → filter-completed → filter-all'],
        v: '每个过滤下卡片状态与计数一致，切回 all 恢复全量',
        shot: 'matrix/todo/todo-02-filter-pending.png',
        neg: false,
      },
      {
        t: '刷新后 todo 状态保持（正向）',
        s: ['将一条 todo 状态改为 completed', '按 F5 硬刷新'],
        v: '刷新后该条仍为 completed（服务端持久），Total 不变',
        shot: 'journeys/todo-j3-done.png',
        neg: false,
      },
      {
        t: '登出重登后数据保持（正向链）',
        s: ['点击 Sign Out 登出', '/login 重新登录 demo 账号', '回到 /todos'],
        v: '重登后列表与服务端一致（增删改结果保留），不丢数据',
        shot: 'matrix/todo/todo-11-login-success.png',
        neg: false,
      },
      {
        t: 'XSS 注入 todo 标题（逆向）',
        s: ['标题输入 <script>alert(1)<\/script>，点击 Add Todo', '查看卡片渲染'],
        v: '标题按纯文本渲染不执行（无弹窗），随后删除清理',
        shot: null,
        neg: true,
      },
      {
        t: '超长标题提交（逆向）',
        s: ['标题粘贴 256+ 字符长串', '点击 Add Todo'],
        v: '实勘：接受则卡片正常换行不溢出且 Total +1；拒绝则提示校验——记录行为，无崩溃',
        shot: null,
        neg: true,
      },
      {
        t: '双击 Add Todo 防重（逆向）',
        s: ['输入标题后快速双击 Add Todo'],
        v: '仅创建 1 条（若重复记录为缺陷），随后清理',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'todo',
    zh: '经典全栈',
    name: 'Todo App',
    site: 'https://todo.lpm1.top',
    identity: '游客（自动登录）',
    pos: 2,
    neg: 1,
    cases: [
      {
        t: '免登录操作 todos',
        s: ['直接打开 /todos'],
        v: '自动登录为 Demo User，可直接增删改',
        shot: 'matrix/todo/01-home.png',
        neg: false,
      },
      {
        t: '登出态访问受保护接口（逆向）',
        s: ['清空 localStorage 后无 token 请求 /api/todos 写接口'],
        v: '返回 401，REST 层要求认证（页面自动登录为 demo 特性，接口层不放松）',
        shot: null,
        neg: true,
      },
      {
        t: '硬刷新后自动登录态保持（正向）',
        s: ['直接打开 /todos', '按 F5 硬刷新后再新增一条'],
        v: '刷新后仍处于自动登录态（可增删改），新条目 Total +1 成功',
        shot: 'matrix/todo/01-home.png',
        neg: false,
      },
    ],
  },
  {
    portalId: 'market',
    zh: '插件市场',
    name: 'XBrowser Marketplace',
    site: 'https://market.lpm1.top',
    identity: '平台管理员',
    pos: 14,
    neg: 6,
    cases: [
      {
        t: '登录管理后台',
        s: ['打开 /admin', '输入 superadmin / 123456', '点击登录'],
        v: '进入管理后台',
        shot: null,
        neg: false,
      },
      {
        t: '插件审核（approve/reject）',
        s: ['进入插件管理页', '查看待审核列表', '点击 approve 或 reject'],
        v: '插件状态变更',
        shot: null,
        neg: false,
      },
      {
        t: '插件上架/下架',
        s: ['进入插件管理页', '操作上架/下架按钮'],
        v: '插件可见性变更',
        shot: null,
        neg: false,
      },
      {
        t: '管理后台登录页（快速登录三按钮）',
        s: ['打开 /admin/login'],
        v: '中文后台 + 超级管理员/客服人员/普通用户快速登录按钮',
        shot: 'matrix/market/market-21-admin-login.png',
        neg: false,
      },
      {
        t: '管理员仪表盘',
        s: ['快速登录超级管理员'],
        v: '统计卡/菜单/测试通知正常；P3：最后更新显示原始 ISO 时间戳',
        shot: 'matrix/market/market-21b-admin-dashboard.png',
        neg: false,
      },
      {
        t: '管理员内容列表',
        s: ['进入内容列表'],
        v: '2 条种子内容 + 编辑操作正常',
        shot: 'matrix/market/market-21c-admin-content-list.png',
        neg: false,
      },
      {
        t: '插件下架入口缺失（逆向·功能缺口实勘）',
        s: [
          'superadmin 登录 /admin 遍历菜单找插件下架入口',
          'API 级 DELETE /api/plugins/not-exist-slug',
        ],
        v: '实勘：管理端无插件下架 UI（菜单仅仪表盘/内容/用户订单/系统，软回退 200）——记录为功能缺口；API 层对不存在 slug 返回 404 不产生副作用',
        shot: null,
        neg: true,
      },
      {
        t: '缺名称的插件表单被拒（逆向）',
        s: ['发布/编辑表单不填名称直接提交'],
        v: '校验拦截并提示必填',
        shot: null,
        neg: true,
      },
      {
        t: '快速登录三按钮逐一验证（正向遍历）',
        s: [
          '打开 /admin（重定向 /admin/login）',
          '依次使用 超级管理员/客服人员/普通用户 三个快速登录按钮（每次登录后登出再试下一个）',
        ],
        v: '超级管理员→/admin/dashboard + toast"已以超级管理员身份登录!"；客服/普通用户的落地页与可见菜单实勘（若与超管同权记越权缺陷）',
        shot: 'matrix/market/market-21-admin-login.png',
        neg: false,
      },
      {
        t: '管理后台硬刷新会话保持（正向）',
        s: [
          '超级管理员登录后 /admin/dashboard 按 F5 硬刷新',
          '直接访问 /admin/content 与系统设置子路由',
        ],
        v: '刷新不回登录页，子路由直访正常渲染；已知 P3：仪表盘"最后更新"显示原始 ISO 时间戳',
        shot: 'matrix/market/market-21b-admin-dashboard.png',
        neg: false,
      },
      {
        t: '内容编辑→还原双向链（正向链）',
        s: [
          '/admin/content 编辑某条内容，标题追加 [T] 保存',
          '列表确认变更',
          '再次编辑移除 [T] 还原',
        ],
        v: '两次保存均即时反映在列表；还原后与初值逐字段一致，无残留',
        shot: 'matrix/market/market-21c-admin-content-list.png',
        neg: false,
      },
      {
        t: '内容新建→删除回收链（正向·实勘新建入口）',
        s: [
          '在 /admin/content 探测新建内容入口（v8 记录行操作仅 编辑/删除）',
          '若可新建：创建 [T-DEL] 内容→列表出现→删除→消失',
          '若入口缺失：记录为功能缺口',
        ],
        v: '实勘：删除后列表行移除且前台不受污染；新建入口缺失则记 SKIP+缺口（与 v8 结论对照）',
        shot: null,
        neg: false,
      },
      {
        t: '分类管理页遍历（正向·实勘）',
        s: ['进入 内容管理→分类管理', '查看列表与增删改能力'],
        v: '实勘：页面真实渲染（非软回退仪表盘壳）；记录当前 CRUD 能力边界；操作后回前台确认无异常',
        shot: null,
        neg: false,
      },
      {
        t: '用户与订单四子页遍历（正向）',
        s: ['依次进入 用户与订单→ 用户/订单/工单/纠纷 四个子页'],
        v: '四页均真实渲染（表格或空态），无一软回退到仪表盘壳；记录各页数据非空性',
        shot: null,
        neg: false,
      },
      {
        t: '系统管理三子页遍历（正向）',
        s: ['依次进入 系统管理→ 角色权限/系统设置/系统日志'],
        v: '角色权限矩阵完整、系统设置表单带真实值、系统日志有记录行；无软回退壳',
        shot: null,
        neg: false,
      },
      {
        t: '插件管理页审核链 approve/reject/下架（正向·新功能实勘）',
        s: [
          'superadmin 登录后进入插件管理页（该 UI 正由开发补建）',
          '查看待审核列表',
          '对 [T] 测试插件执行 approve、对另一条执行 reject',
          '对已上架插件执行下架并回前台对照',
        ],
        v: '实勘：状态流转 pending→approved/rejected 正确且 /developer 视角可见；下架后前台插件列表不再显示该插件（v8 时点管理端无插件菜单，若本次仍无 UI 则维持缺口记录）',
        shot: null,
        neg: false,
      },
      {
        t: '未知 /admin/* 路由软回退（逆向边界）',
        s: ['直访 /admin/plugins', '再直访 /admin/not-exist-xyz'],
        v: '实勘（v8 已记录）：HTTP 200 回退仪表盘壳、无 404 页——复核该行为是否仍存在；无崩溃无数据泄露，维持 soft-404 缺口记录',
        shot: null,
        neg: true,
      },
      {
        t: '错误密码登录管理后台（逆向）',
        s: ['/admin/login 输入 superadmin / wrong-pass 提交'],
        v: '报错停留登录页，不进入 dashboard；无半渲染的管理数据泄露',
        shot: null,
        neg: true,
      },
      {
        t: '客服人员越权探测（身份交叉·实勘）',
        s: [
          '以客服人员快速登录',
          '尝试直访系统管理子页与（新建的）插件管理页',
          '尝试执行编辑/删除写操作',
        ],
        v: '实勘：客服应仅只读/受限——无权限处应 403 或按钮隐藏；若可执行管理写操作记越权缺陷',
        shot: null,
        neg: true,
      },
      {
        t: '游客与普通用户 token 调管理 API（身份交叉·逆向）',
        s: [
          '无 Authorization 请求 GET /api/admin/stats、/api/admin/users',
          '用前台普通用户（markettest0912@t.com / Test1234!）的 JWT 带 Bearer 重复请求',
        ],
        v: '无 token 401；普通用户 403 不泄露任何管理数据（对照 fullstack preset 的 Permission denied 行为，实勘 market 后端）',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'market',
    zh: '插件市场',
    name: 'XBrowser Marketplace',
    site: 'https://market.lpm1.top',
    identity: '开发者',
    pos: 8,
    neg: 10,
    cases: [
      {
        t: '注册开发者账号',
        s: ['打开注册页', '填写用户名/邮箱/密码', '提交'],
        v: '注册成功跳转登录',
        shot: null,
        neg: false,
      },
      {
        t: '提交插件',
        s: ['登录后点击 Publish', '填写插件信息（名称/描述/版本/仓库）', '提交'],
        v: '插件进入 pending 审核状态',
        shot: null,
        neg: false,
      },
      {
        t: '查看审核状态',
        s: ['进入 Developer 页面', '查看自己的插件列表'],
        v: '显示各插件的 pending/approved/rejected 状态',
        shot: null,
        neg: false,
      },
      {
        t: '开发者控制台角色守卫（逆向）',
        s: ['普通用户登录后访问 /developer'],
        v: '⚠ P2：静默弹回 /login，无任何权限提示',
        shot: 'matrix/market/market-20-developer-guard-redirect-login.png',
        neg: true,
      },
      {
        t: '直连 /developer URL 守卫确认',
        s: ['地址栏直接输入 /developer'],
        v: '同样弹回 /login（角色守卫生效但无提示）',
        shot: 'matrix/market/market-20c-developer-direct-url-redirect.png',
        neg: false,
      },
      {
        t: '/publish 发布表单（普通用户可访问）',
        s: ['登录态访问 /publish'],
        v: '完整表单（名称/Slug/描述/仓库/NPM/License）可访问',
        shot: 'matrix/market/market-20d-publish-form.png',
        neg: false,
      },
      {
        t: 'demo 预填凭据登录（逆向）',
        s: ['/login 直接用预填 developer@pluginhub.io 登录'],
        v: '⚠ P2：预填凭据报 Invalid credentials（demo 凭据失效）',
        shot: 'matrix/market/market-20b-demo-credentials-invalid.png',
        neg: true,
      },
      {
        t: '注册→登录→发布插件完整链（正向闭环）',
        s: [
          '/register 注册新账号（placeholder 定位 Choose a username / Enter your email / Choose a password）',
          '提交后跳 /login，登录新号（React 受控输入需 nativeInputValueSetter 注入）',
          '/publish 填全 7 字段（Plugin Name/Slug/Description/Repository URL/Homepage URL/NPM Package/License）',
          '点 Publish Plugin 提交',
        ],
        v: '提交成功有明确反馈（toast/跳转/pending 徽章，实勘具体形态）；新插件不出现在前台列表（待审核）',
        shot: 'matrix/market/market-20d-publish-form.png',
        neg: false,
      },
      {
        t: '发布表单逐必填缺失（逆向）',
        s: ['依次仅留空 Name / Slug / Description 各提交一次（其余字段填全）'],
        v: '每次均被 HTML5 required 拦截（原生"请填写此字段。"，v8 已验 Name 分支），停留 /publish、无 toast、不产生插件数据',
        shot: 'matrix/market/market-20d-publish-form.png',
        neg: true,
      },
      {
        t: 'Slug 非法字符（逆向·实勘）',
        s: ['/publish Slug 分别填 "Auth Guard!!"（空格+叹号）与纯中文，其余字段合法提交'],
        v: '实勘：预期被校验拒绝或自动 slugify 规范化；若入库产生含空格/中文 slug 记缺陷（后续 /plugins/<slug> URL 不可达）',
        shot: null,
        neg: true,
      },
      {
        t: 'Slug 与现有插件冲突（逆向）',
        s: ['/publish 正常填表但 Slug 填 auth-guard 提交'],
        v: '实勘：预期 409/唯一约束报错且表单保留；若成功创建重复 slug 记 P1（前台路由冲突）',
        shot: null,
        neg: true,
      },
      {
        t: '超长 256+ 名称与描述（逆向）',
        s: ['Plugin Name 填 256+ 字符、Description 填 2000+ 字符提交'],
        v: '被校验拒绝或安全截断；提交后 /publish 与前台列表均不破版、无 500',
        shot: null,
        neg: true,
      },
      {
        t: 'HTML 注入插件名（逆向）',
        s: ['Plugin Name 填 <script>alert(1)<\/script>，其余字段合法，提交'],
        v: '无 alert 执行；实勘是否创建成功——若成功，确认卡片/列表转义显示并记录脏数据；若拒绝，确认提示明确',
        shot: null,
        neg: true,
      },
      {
        t: '/developer 我的插件列表状态（正向·角色实勘）',
        s: ['发布插件后点导航 [data-testid="nav-developer-button"] 进 /developer'],
        v: '实勘：已知普通用户被静默弹回 /login（P2 无权限提示）——若本次开发者角色可见列表，核对自己插件与 pending/approved 状态显示；若仍弹回则维持缺口记录',
        shot: 'matrix/market/market-20-developer-guard-redirect-login.png',
        neg: false,
      },
      {
        t: '双击重复提交发布（逆向）',
        s: ['/publish 填全合法表单后快速双击 Publish Plugin'],
        v: '仅创建 1 条插件记录（实勘 API 幂等性），无重复 slug/重复行',
        shot: null,
        neg: true,
      },
      {
        t: '伪造 Bearer token 调发布 API（逆向·实勘）',
        s: ['登出态以 Authorization: Bearer fake123 直接 POST /api/plugins（合法 JSON 体）'],
        v: '实勘：预期 401；若 mock 放行创建记 P1 认证旁路（该 mock 曾自动写入 Demo User token，重点勘鉴权层）',
        shot: null,
        neg: true,
      },
      {
        t: '游客直访 /publish 与 /developer（身份交叉·实勘）',
        s: ['真登出态（清 localStorage 后）分别直访 /publish 与 /developer'],
        v: '实勘：预期均引导/弹回登录（/developer 已知静默弹 /login 且无提示）；记录 /publish 游客态实际行为（v8 时点未勘），无表单提交成功',
        shot: null,
        neg: true,
      },
      {
        t: 'demo 预填凭据正向重登（v7 修复复验）',
        s: [
          '/login 保留预填 demo@biomimic.app/demo123 直接点 [data-testid="login-submit"]',
          '观察落地页与导航身份',
        ],
        v: '登录成功落地 /plugins，导航显示 demo + Sign Out；旧"Invalid credentials"缺陷不复现（v4 WARNING 已过时）',
        shot: 'matrix/market/market-15b-login-page.png',
        neg: false,
      },
    ],
  },
  {
    portalId: 'market',
    zh: '插件市场',
    name: 'XBrowser Marketplace',
    site: 'https://market.lpm1.top',
    identity: '用户/浏览器用户',
    pos: 12,
    neg: 13,
    cases: [
      {
        t: '浏览插件市场',
        s: ['打开首页'],
        v: '插件卡片渲染（Auth Guard / AI Helper）',
        shot: 'matrix/market/market-01.png',
        neg: false,
      },
      {
        t: '搜索插件',
        s: ['点击导航 Search', '输入 auth', '提交搜索'],
        v: 'Found 1 results，仅 Auth Guard',
        shot: 'matrix/market/market-03-search-auth.png',
        neg: false,
      },
      {
        t: '查看插件详情',
        s: ['点击 Auth Guard 卡片'],
        v: '详情页显示 approved/Featured/v1.0.0',
        shot: 'matrix/market/market-04-auth-guard-detail.png',
        neg: false,
      },
      {
        t: '安装插件',
        s: ['在详情页点击 Install Plugin'],
        v: '后端 POST 200（UI 反馈为已知缺陷）',
        shot: 'matrix/market/market-05-install-click.png',
        neg: false,
      },
      {
        t: '写评论（逆向：静默失败）',
        s: ['在详情页评论表单填写 5 星+标题+正文', '点击提交'],
        v: '⚠ POST 404 Plugin not found，UI 清空表单假装成功（已知缺陷）',
        shot: 'matrix/market/market-07-review-after-submit.png',
        neg: true,
      },
      {
        t: '注册并登录（2026-09-12 补拍）',
        s: ['注册 markettest0912@t.com', '登录'],
        v: '右上角显示 markettest0912（⚠ 落地 /todos 404 为已知 P2）',
        shot: 'matrix/market/market-16b-logged-in-home.png',
        neg: false,
      },
      {
        t: '登录后落地页（逆向：404）',
        s: ['登录成功观察跳转'],
        v: '⚠ P2 BUG：跳 /todos 渲染 404（冷会话稳定复现）',
        shot: 'matrix/market/market-16-postlogin-404.png',
        neg: true,
      },
      {
        t: '登录态点 Install（逆向：零反馈）',
        s: ['登录态在详情页点 Install Plugin'],
        v: '⚠ P1 BUG：按钮/计数/URL 全无变化，登录态同样复现',
        shot: 'matrix/market/market-17-install-logged-in-no-change.png',
        neg: true,
      },
      {
        t: '评论提交后刷新验证（逆向：未入库）',
        s: ['提交评论后 F5 刷新'],
        v: '⚠ P1 BUG：刷新后仍 No reviews yet，评论未持久化',
        shot: 'matrix/market/market-18b-review-after-reload.png',
        neg: true,
      },
      {
        t: '个人中心（逆向：硬编码 + 入口缺失）',
        s: ['访问 /profile', '探测 /account /me /installed /my-plugins'],
        v: '⚠ P2：profile 硬编码 Jane Doe；全站无"我的安装"页',
        shot: 'matrix/market/market-19-profile-janedoe-hardcoded.png',
        neg: true,
      },
      {
        t: '我的安装页列表',
        s: ['登录后导航点击"我的安装"（/installed）'],
        v: '列出当前用户已安装插件（名称/版本/安装时间），无旧 mock 数据',
        shot: 'matrix/market/market-16b-logged-in-home.png',
        neg: false,
      },
      {
        t: '卸载已安装插件',
        s: ['在 /installed 点击卸载', '回详情页重新 Install'],
        v: '卸载后列表移除、重装恢复，installed 状态服务端驱动',
        shot: null,
        neg: false,
      },
      {
        t: '未登录访问我的安装（逆向）',
        s: ['登出后直接访问 /installed'],
        v: '401 由 apiClient 统一跳转 /login，不泄露安装数据',
        shot: null,
        neg: true,
      },
      {
        t: '重复安装幂等（逆向）',
        s: ['同一插件连续点击 Install 两次'],
        v: '安装记录唯一（UNIQUE 约束幂等），计数仅累加、不产生重复安装行',
        shot: null,
        neg: true,
      },
      {
        t: '安装→刷新按钮复位→下载量持久链（v6 复验深化）',
        s: [
          '登录态详情页点 [data-testid="install-button"]（记当前下载量 N）',
          '确认按钮变 Installed ✓（绿色 disabled）+ toast Installed successfully',
          'F5 刷新回详情页',
          '再次 Install',
        ],
        v: '首次点击 N→N+1；刷新后按钮复位 Install Plugin 但下载量保持 N+1（入库）；重装再 +1（累计不重置）',
        shot: 'matrix/market/market-05-install-click.png',
        neg: false,
      },
      {
        t: '安装→卸载→重装下载量单调链（正向闭环）',
        s: [
          '安装 auth-guard 后打开 /installed（导航 我的安装）确认条目',
          '点 [data-testid="uninstall-auth-guard"] 卸载',
          '回详情页重装 → 再回 /installed 核对',
        ],
        v: '卸载后条目立即消失且 downloads 不回退；重装后条目复现（0→1）、downloads 净 +2——安装计数只增不减为断言核心',
        shot: null,
        neg: false,
      },
      {
        t: '我的安装空态 Browse CTA（正向边界）',
        s: ['卸载全部已装插件后打开 /installed', '点击空态页 Browse Plugins CTA'],
        v: '显示 No installs yet + Browse Plugins CTA；点击 CTA 可跳回插件列表（实勘链接目标）',
        shot: null,
        neg: false,
      },
      {
        t: '评论提交失败真实反馈（v6 复验·已知服务端 500）',
        s: [
          '详情页评论表单选 5 星 + 填标题 + 填正文',
          '提交（Submit Review 无 testid，runtime-tag data-uitest 后真点）',
        ],
        v: '表单保留不清空 + [data-testid="review-error"] 红框 Failed to submit review + Reviews 计数不变（旧"静默假装成功"已修；服务端 500 {success:false} 为已知残留，成功分支不可达）',
        shot: 'matrix/market/market-06-review-filled.png',
        neg: true,
      },
      {
        t: '评论无星级提交被拒（逆向·实勘）',
        s: ['只填标题与正文、不点任何星级，提交'],
        v: '实勘：预期 rating 必填校验（前端禁用/后端 400）；若以 0 星入库或 500 静默，记录实际行为与缺陷级别',
        shot: null,
        neg: true,
      },
      {
        t: '评论超长文本边界（逆向·实勘）',
        s: ['评论正文输入 2000+ 字符提交'],
        v: '实勘：被截断/校验拒绝，或因服务端 500 走失败红框分支；无论何分支不得 XSS/破版，表单行为与失败反馈用例一致',
        shot: null,
        neg: true,
      },
      {
        t: '搜索+分类 chip 组合语义（正向深化·实勘）',
        s: [
          '搜索 auth 得 Found 1 results',
          '依次点击结果页下方 All / wrench工具 / sparklesAI chips',
          '清空关键词回 All',
        ],
        v: '实勘：chip 是否参与结果过滤（已知 chip 状态从侧栏泄漏高亮、AI 分类 0 匹配）——记录组合矩阵实际行为，结果集与视觉高亮一致即通过',
        shot: 'matrix/market/market-12.png',
        neg: false,
      },
      {
        t: '分类筛选工具→0→All 往返（v6 行为复核）',
        s: ['首页侧栏点 wrench工具 分类', '观察列表与空态', '点回 All Plugins'],
        v: '工具分类 2→0 卡 + active 高亮 + No plugins found 空态；All 恢复 2 卡（v6 已验 PASS；AI 分类同 0 为已知 payload 无 category 字段）',
        shot: null,
        neg: false,
      },
      {
        t: '不存在插件 slug 直访（逆向·实勘）',
        s: ['地址栏直接打开 /plugins/not-exist-slug-xyz'],
        v: '实勘：预期 404/空态兜底而非白屏；对照 POST /api/plugins/not-exist-slug 的 404 行为，记录 UI 层实际形态',
        shot: null,
        neg: true,
      },
      {
        t: '删除他人评论 API 越权（IDOR·身份交叉·实勘）',
        s: ['以自己 JWT DELETE /api/plugins/auth-guard/reviews/<伪造id>，再以他人资源 id 重试'],
        v: '实勘：预期 403/404 且无副作用（评论区服务端写入当前 500，可能无可操作真实 id——记录 API 鉴权层实际响应码）',
        shot: null,
        neg: true,
      },
      {
        t: '普通用户 token 调管理 API（身份交叉·逆向）',
        s: [
          '以普通用户 JWT 请求 GET /api/admin/stats、/api/admin/users',
          'UI 侧确认前台导航无任何管理入口',
        ],
        v: 'API 403 不泄露数据；UI 无 /admin 入口（管理端为独立登录体系，普通用户 token 不可复用为管理员身份——实勘确认）',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'market',
    zh: '插件市场',
    name: 'XBrowser Marketplace',
    site: 'https://market.lpm1.top',
    identity: '游客（未登录）',
    pos: 11,
    neg: 13,
    cases: [
      {
        t: '浏览插件列表',
        s: ['直接打开首页'],
        v: '插件卡片可见',
        shot: 'matrix/market/market-01.png',
        neg: false,
      },
      {
        t: '搜索（不需登录）',
        s: ['点击 Search', '输入关键词', '提交'],
        v: '搜索结果正常',
        shot: 'matrix/market/market-03-search-auth.png',
        neg: false,
      },
      {
        t: '空结果态',
        s: ['搜索不存在的词 zzzqqq'],
        v: '显示 No results for zzzqqq',
        shot: null,
        neg: false,
      },
      {
        t: '首页完整卡片墙（真实游客态，2026-09-12 补拍）',
        s: ['Sign Out 后打开首页'],
        v: '卡片墙 + 分类侧栏 + Login 入口',
        shot: 'matrix/market/market-10.png',
        neg: true,
      },
      {
        t: '分类筛选（逆向：no-op）',
        s: ['点击分类侧栏"工具"'],
        v: '⚠ P1 BUG：列表不变（API payload 无 category 字段），仅 chip 高亮',
        shot: 'matrix/market/market-11.png',
        neg: true,
      },
      {
        t: '搜索 "ai" 结果页',
        s: ['搜索 ai'],
        v: 'Found 1 results → AI Helper；P3：chip 状态泄漏高亮',
        shot: 'matrix/market/market-12.png',
        neg: false,
      },
      {
        t: '详情页上半部',
        s: ['打开插件详情'],
        v: '描述/评分/作者/徽章齐全；P3：发布日期 1970/1/1',
        shot: 'matrix/market/market-13.png',
        neg: false,
      },
      {
        t: '详情页下半部（评论区 + 版本历史探测）',
        s: ['详情页滚动到底'],
        v: 'Reviews(0) 空态 + 评论表单；缺口：版本历史区块不存在',
        shot: 'matrix/market/market-14.png',
        neg: false,
      },
      {
        t: '游客点 Install（逆向：零反馈不鉴权）',
        s: ['未登录点 Install Plugin'],
        v: '⚠ P1 BUG：无任何反应也不跳登录（URL/按钮/计数全不变）',
        shot: 'matrix/market/market-15.png',
        neg: true,
      },
      {
        t: '登录页（游客入口）',
        s: ['点导航 Login'],
        v: '/login 渲染正常（预填凭据问题另案）',
        shot: 'matrix/market/market-15b-login-page.png',
        neg: true,
      },
      {
        t: '移动端首页（375px）',
        s: ['切 375x812 视口打开首页'],
        v: 'hero/CTA/卡片/底部 tab（Discover/Plugins/Categories/Search/My）完整',
        shot: 'matrix/market/market-22-mobile-home.png',
        neg: false,
      },
      {
        t: '移动端详情页',
        s: ['375px 打开详情'],
        v: 'hero/Install/评分/评论表单完整',
        shot: 'matrix/market/market-23-mobile-detail.png',
        neg: false,
      },
      {
        t: '移动端搜索结果',
        s: ['375px 搜索 ai'],
        v: 'Found 1 results + Search tab 高亮',
        shot: 'matrix/market/market-24-mobile-search.png',
        neg: false,
      },
      {
        t: '硬刷新详情页（边界）',
        s: ['详情页直连 URL 冷加载'],
        v: '无白屏无 hydration 错误；注意头部身份漂移怪癖（显示 Demo User）',
        shot: 'matrix/market/market-25-hard-refresh-detail.png',
        neg: false,
      },
      {
        t: '真游客态工艺链（前置·自动登录怪癖）',
        s: ['eval 清空 localStorage + sessionStorage + cookie 后 reload 首页'],
        v: '导航显示 Login（app 首载会自动写入 Demo User auth-token，清空后不再写入——v8 gotcha）；本用例为后续游客用例统一前置',
        shot: 'matrix/market/market-10.png',
        neg: true,
      },
      {
        t: '游客访问 /installed 引导卡（v8 确认）',
        s: ['真游客态直访 /installed'],
        v: '不跳转 /login：页内渲染引导卡 Sign in to see your installed plugins + "Your install history is tied to your account." + Sign In 紫钮；导航身份为 Login（旧断言"401 跳登录"已被该行为取代）',
        shot: null,
        neg: true,
      },
      {
        t: '游客点 Install（实勘·v6 后行为）',
        s: [
          '真游客态在详情页点 [data-testid="install-button"]',
          '观察按钮/toast/下载量/URL 四要素',
        ],
        v: '实勘：预期 401 反馈或登录引导（旧"零反馈不鉴权"可能随 v6 反馈修复而变化，见历史截图对照）；下载量不得增加、不得产生归属不明的安装记录',
        shot: 'matrix/market/market-15.png',
        neg: true,
      },
      {
        t: '游客评论表单可见性（身份交叉·实勘）',
        s: ['真游客态打开详情页滚动至评论表单'],
        v: '实勘：market 是否与 forum 一致隐藏表单/灰条引导，或仍渲染可提交表单——若可提交，预期 401 失败红框（对照评论失败反馈用例分支）；记录实际形态',
        shot: 'matrix/market/market-14.png',
        neg: true,
      },
      {
        t: '游客直访 /publish 与 /developer（身份交叉）',
        s: ['真游客态分别直访 /publish、/developer'],
        v: '均引导/弹回登录（/developer 已知静默弹 /login 为 P2 无提示——游客态复验同一行为；/publish 游客行为实勘）；无插件表单提交成功',
        shot: null,
        neg: true,
      },
      {
        t: '游客调管理 API（身份交叉·逆向）',
        s: ['无 Authorization 请求 GET /api/admin/stats'],
        v: '401，响应体无任何统计/用户数据（管理端为独立登录体系）',
        shot: null,
        neg: true,
      },
      {
        t: '伪造 Bearer token 调安装 API（逆向·实勘）',
        s: ['Authorization: Bearer fake123 直接 POST /api/plugins/auth-guard/install'],
        v: '实勘：预期 401/403；若 mock 放行记 P1 认证旁路并核对安装记录归属（mock 自动登录 token 为已知风险面）',
        shot: null,
        neg: true,
      },
      {
        t: '分页参数越界（逆向·实勘）',
        s: ['GET /api/plugins?page=999', 'GET /api/plugins?page=-1 与 page=abc 两组对照'],
        v: '实勘：预期空数组 200 或 400 校验错，不 500 不崩；当前无分页 UI 则记录 API 层结论即可',
        shot: null,
        neg: true,
      },
      {
        t: '搜索注入串（逆向）',
        s: ["搜索框输入 ' OR 1=1 -- 提交", '再输入 <script>alert(1)<\/script> 提交'],
        v: '显示 No results for "<原文>" 转义空态（或实勘意外命中并记录），无脚本执行、服务端不 500；搜索框内容可清空恢复',
        shot: null,
        neg: true,
      },
      {
        t: '移动端底部 tab 全遍历（375px·正向）',
        s: [
          '375x812 视口打开首页',
          '依次点 bottom-tab-discover / bottom-tab-plugins / bottom-tab-categories / bottom-tab-search / bottom-tab-my / bottom-tab-我的安装',
        ],
        v: '各 tab 全部可达对应路由（/plugins、/plugins/list、categories、search、/developer、/installed），激活态蓝色高亮；桌面导航在 375px 隐藏为已知',
        shot: 'matrix/market/market-22-mobile-home.png',
        neg: false,
      },
    ],
  },
  {
    portalId: 'forum',
    zh: '社区论坛',
    name: 'Forum',
    site: 'https://forum.lpm1.top',
    identity: '管理员',
    pos: 10,
    neg: 5,
    cases: [
      {
        t: '内容新建/编辑/发布',
        s: ['登录管理后台', '进入内容管理', '新建内容 → 填写 → 发布'],
        v: '内容状态变为 published',
        shot: null,
        neg: false,
      },
      { t: '用户管理', s: ['进入用户管理页'], v: '用户列表正常渲染', shot: null, neg: false },
      { t: '系统设置', s: ['进入系统设置页'], v: '表单带出真实配置值', shot: null, neg: false },
      {
        t: '空标题内容创建被拒（逆向）',
        s: ['登录管理后台内容管理', '新建内容不填标题直接提交'],
        v: '校验拦截并提示必填，不产生脏数据',
        shot: null,
        neg: true,
      },
      {
        t: '未登录访问管理 API（逆向）',
        s: ['不带 Authorization 请求管理端接口'],
        v: '返回 401',
        shot: null,
        neg: true,
      },
      {
        t: '编辑内容后还原（正向链）',
        s: [
          '打开 https://forum.lpm1.top/admin 登录 superadmin / 123456，进入内容管理',
          '编辑 content-1，标题末尾追加 [T-EDIT] 保存',
          '打开前台 /content/content-1 确认标题已带 [T-EDIT]',
          '返回管理后台再次编辑，移除 [T-EDIT] 还原',
        ],
        v: '前台标题两阶段变化并可完整还原；还原后前台与后台列表均无测试残留（断言以变化前后对照为准，content-1 标题含历史测试残留 {fa-super} 勿锚定纯文本）',
        shot: null,
        neg: false,
      },
      {
        t: '草稿→发布状态切换（正向）',
        s: [
          '管理后台内容管理新建内容（标题含 [T-DRAFT] 标记，存为草稿/draft）',
          '打开前台首页确认该内容不出现在列表',
          '管理端将其状态切换为 published',
          '刷新前台首页确认出现',
        ],
        v: '实勘：前台列表只显示 published 内容、草稿不可见；发布后可见（若前台无草稿过滤则记录为缺陷）',
        shot: null,
        neg: false,
      },
      {
        t: '新建内容→删除回收链（正向）',
        s: [
          '新建内容 [T-DEL-回收测试] 并发布',
          '前台确认可见后，管理端删除该内容',
          '前台首页列表与 /content/<id> 直访复查',
        ],
        v: '删除后首页列表不再出现，直访返回 404 兜底页；种子内容 content-1/content-2 不受影响',
        shot: null,
        neg: false,
      },
      {
        t: '分类管理新建分类（正向·实勘）',
        s: [
          '管理后台进入 内容管理→分类管理',
          '查看现有分类列表',
          '新建分类 [T-分类] 保存',
          '打开前台首页观察筛选胶囊区',
        ],
        v: '实勘：分类列表渲染正常；前台筛选胶囊当前固定 6 个（全部/文章/公告/教程/新闻/政策），新分类是否映射到前台胶囊待勘（不映射则记录前后端不同步）',
        shot: null,
        neg: false,
      },
      {
        t: '用户管理搜索过滤（正向）',
        s: ['管理后台进入用户管理（/admin/users）', '在搜索框输入 superadmin', '清空搜索恢复全表'],
        v: '搜索后表格仅剩 superadmin 行；清空后恢复完整列表且行数与初始一致',
        shot: null,
        neg: false,
      },
      {
        t: '管理后台硬刷新会话保持（正向）',
        s: ['登录管理后台到达 /admin/dashboard', '按 F5 硬刷新', '再直接访问 /admin/users 子路由'],
        v: '刷新后仍停留 dashboard 不回登录页；子路由直访正常渲染（实勘 token 存储位置与有效期）',
        shot: null,
        neg: false,
      },
      {
        t: '同一内容连续两次编辑（连续操作）',
        s: [
          '编辑 content-2 摘要追加 A → 保存',
          '立即再次编辑追加 B → 保存',
          '打开前台 /content/content-2 对照最终内容',
        ],
        v: '前台显示两次编辑叠加后的最终内容，无中间态丢失或字段回滚',
        shot: null,
        neg: false,
      },
      {
        t: '错误密码登录管理后台（逆向）',
        s: ['/admin 登录页输入 superadmin / wrong-pass-123', '点击登录'],
        v: '提示凭据错误并停留登录页；地址栏不进入 /admin/dashboard，无任何管理数据渲染',
        shot: null,
        neg: true,
      },
      {
        t: '超长+HTML 注入内容标题（逆向）',
        s: [
          '新建内容，标题填 256+ 字符并在末尾拼 <script>alert(1)<\/script>',
          '提交保存',
          '打开前台首页与该内容详情页',
        ],
        v: '超长被校验拒绝或安全截断；脚本串以纯文本转义显示、无 alert 执行；首页列表布局不破版',
        shot: null,
        neg: true,
      },
      {
        t: '无 token / 普通用户 token 调管理 API（逆向·身份交叉）',
        s: [
          '无 Authorization 请求 GET /api/admin/users 与 /api/admin/stats',
          '用前台注册用户（round2verify@t.com / Test1234!）登录取 JWT 后带 Bearer 重复请求',
        ],
        v: '无 token 一律 401；普通用户 token 403（实勘 forum 后端角色校验，若放行记 P1 越权）',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'forum',
    zh: '社区论坛',
    name: 'Forum',
    site: 'https://forum.lpm1.top',
    identity: '注册用户',
    pos: 19,
    neg: 11,
    cases: [
      {
        t: '注册/登录',
        s: ['打开 /register', '填写表单', '提交', '登录'],
        v: '注册→登录成功',
        shot: 'matrix/forum/06-register.png',
        neg: false,
      },
      {
        t: '浏览全部内容',
        s: ['打开首页'],
        v: '全部已发布内容可见',
        shot: 'matrix/forum/01-home.png',
        neg: false,
      },
      {
        t: '分类筛选',
        s: ['点击"文章"筛选胶囊'],
        v: '列表缩至仅文章类',
        shot: 'matrix/forum/02-filter-article.png',
        neg: false,
      },
      {
        t: '搜索',
        s: ['输入 ISR', '点击搜索'],
        v: '命中 ISR 教程',
        shot: 'matrix/forum/03-search-isr.png',
        neg: false,
      },
      {
        t: '查看内容详情',
        s: ['点击内容卡片'],
        v: '详情页完整（面包屑/正文/返回）',
        shot: 'matrix/forum/04-detail-welcome.png',
        neg: false,
      },
      {
        t: '登录后首页身份展示（2026-09-12 补拍）',
        s: ['/login 点 Sign In（预填凭据）', '回到首页'],
        v: 'navbar 显示 Demo User + Sign Out，2 卡正常',
        shot: 'matrix/forum/forum-10.png',
        neg: false,
      },
      {
        t: '登录后详情页评论区探测',
        s: ['登录态打开内容详情页'],
        v: '⚠ 缺口：评论区整体不存在（无输入框/无评论文案）',
        shot: 'matrix/forum/forum-21.png',
        neg: false,
      },
      {
        t: 'Profile 登录后内容（逆向：硬编码）',
        s: ['登录态访问 /profile'],
        v: '⚠ BUG：与游客态相同的 Jane Doe 硬编码档案，与登录身份无关',
        shot: 'matrix/forum/forum-23.png',
        neg: true,
      },
      {
        t: '登录落地死路（逆向）',
        s: ['在 /login 点击 Sign In 观察跳转'],
        v: '⚠ P1 BUG：登录成功跳 /todos → forum preset 无此路由 404',
        shot: 'matrix/forum/forum-29.png',
        neg: true,
      },
      {
        t: '硬刷新详情页（SSR 水合验证）',
        s: ['详情页 F5', '300ms 与 1200ms 双探针'],
        v: '300ms 内容完整无白屏；__SSR_DATA__ 水合后移除',
        shot: 'matrix/forum/forum-27.png',
        neg: false,
      },
      {
        t: '登出后首页',
        s: ['点击 Sign Out'],
        v: 'navbar 变 Login，列表内容不受影响',
        shot: 'matrix/forum/forum-28.png',
        neg: false,
      },
      {
        t: '发表评论',
        s: ['登录态打开内容详情', '输入评论并发布'],
        v: '评论出现在列表且计数 +1，F5 后持久',
        shot: 'matrix/forum/forum-13.png',
        neg: false,
      },
      {
        t: '删除自己的评论',
        s: ['在自己评论旁点击删除'],
        v: '评论移除、计数 -1，他人评论不受影响',
        shot: null,
        neg: false,
      },
      {
        t: '删除他人评论被拒（逆向）',
        s: ['尝试删除他人评论（UI 无按钮；API 层 DELETE 他人评论）'],
        v: 'UI 无入口；API 层 403，仅作者与 super_admin 可删',
        shot: null,
        neg: true,
      },
      {
        t: '三入口到达同一内容详情（入口交叉）',
        s: [
          '登录后首页点击 ISR 教程卡（a[href="/content/content-2"]）进详情',
          '返回后从导航 Topics（[data-testid="nav-topics-button"]）点击同一内容链接（/topics/content-2 风格）',
          '再从 Popular 页点击同一内容',
        ],
        v: '三个入口均渲染完整详情页（标题/正文/评论区一致）；Topics 的 /topics/content-N 路由不 404（v9 起该路由渲染完整详情）',
        shot: null,
        neg: false,
      },
      {
        t: '搜索+分类组合查询（正向深化）',
        s: [
          '点击"教程"胶囊过滤出 ISR 教程',
          '保持筛选，在搜索框输入 ISR 并点搜索',
          '切回"全部"胶囊观察结果',
        ],
        v: '教程+ISR 组合仅命中 ISR 教程卡；切回全部后符合组合语义（实勘：搜索与分类是否正交——已知 v4 观察为搜索不重置分类，若行为相反记回归）',
        shot: 'matrix/forum/forum-12.png',
        neg: false,
      },
      {
        t: '刷新状态保持双向（登录保持/登出不复活）',
        s: [
          '登录后首页按 F5 硬刷新，确认右上角仍为登录用户名 + Sign Out',
          '点击 Sign Out 后再次 F5',
          '检查 localStorage 的 auth-token 是否保持登出态',
        ],
        v: '登录态刷新身份不变；登出后硬刷新 navbar 保持 Login、auth store 不自动恢复（v8 修复复验，若复活记 P1 回归）',
        shot: 'matrix/forum/forum-10.png',
        neg: false,
      },
      {
        t: '登录落地页 /topics 断言（v8 复验）',
        s: [
          '/login 使用 round2verify@t.com / Test1234! 点 [data-testid="login-submit"]',
          '观察跳转目标（0s / 2s 双帧）',
        ],
        v: '登录成功落地 /topics（h1 Topics 聚合视图）；历史缺陷"跳 /todos 404"与"停留 /"均不复现',
        shot: null,
        neg: false,
      },
      {
        t: 'emoji/中英混合评论提交（正向）',
        s: [
          '登录态打开 /content/content-1 评论区（[data-testid="comment-section"]）',
          '在 [data-testid="comment-input"] 输入 "Great! 🚀 中英混合 test 123"',
          '点 [data-testid="comment-submit"]，随后 F5 刷新',
        ],
        v: '发布成功：评论计数 +1、列表插入且 emoji/中英原样显示、0/2000 计数器工作；F5 后评论持久（服务端持久化）',
        shot: 'matrix/forum/forum-13.png',
        neg: false,
      },
      {
        t: '接近 2000 字长评论边界（正向边界）',
        s: [
          '评论区输入 1999 字符中英混合长文本',
          '发布成功后再输入超限文本，观察计数器与提交按钮状态',
        ],
        v: '1999 字符可发布且完整显示；超限输入被计数器/禁用态拦截或截断（实勘 2000 上限的具体截断行为）',
        shot: null,
        neg: false,
      },
      {
        t: '连续发 3 删 2 计数链（连续操作）',
        s: [
          '连续发布评论 A、B、C 三条',
          '删除 B、C（仅自己评论渲染 [data-testid="comment-delete"]，无确认弹窗）',
          'F5 刷新核对剩余内容',
        ],
        v: '计数 N→N+3→N+1 逐步正确；剩余 A 位置顺序保持；刷新后与服务端一致',
        shot: null,
        neg: false,
      },
      {
        t: '双击重复提交评论（逆向）',
        s: ['输入一条正常评论', '快速双击发布按钮'],
        v: '仅产生 1 条评论（计数 +1），无重复条目（若 +2 记录缺陷，后端幂等性实勘）',
        shot: null,
        neg: true,
      },
      {
        t: '纯空格评论被拒（逆向）',
        s: ['评论框只输入空格（如 5 个空格）', '观察提交按钮状态并尝试提交'],
        v: '按钮呈 disabled 禁用态或提交被拦截；计数不变、不产生空白评论',
        shot: null,
        neg: true,
      },
      {
        t: 'HTML/script 注入评论（逆向）',
        s: ['提交评论 "<script>alert(1)<\/script>"', '再提交 "<img src=x onerror=alert(2)>"'],
        v: '无任何 alert 执行；评论区以转义纯文本渲染；控制台无意外报错',
        shot: null,
        neg: true,
      },
      {
        t: '注册密码 5 位被拒（逆向）',
        s: [
          '/register 填写 username/email，密码填 abc12（5 位）',
          '点 Create Account（form button[type="submit"]）',
        ],
        v: 'min 6 chars 校验拦截（原生 validationMessage 或红字提示）；不跳转 /login、不产生账号',
        shot: 'matrix/forum/06-register.png',
        neg: true,
      },
      {
        t: '注册已存在邮箱被拒（逆向）',
        s: ['/register 使用已存在邮箱 r7other@t.com 与新用户名注册', '提交'],
        v: '服务端报错（实勘具体文案），停留注册/登录页且不产生重复账号；r7other 原账号仍可正常登录',
        shot: null,
        neg: true,
      },
      {
        t: '错误密码登录（逆向）',
        s: ['/login 填 round2verify@t.com / WrongPass!', '点 [data-testid="login-submit"]'],
        v: '[data-testid="login-error"] 显示 Invalid credentials、停留 /login 不跳转；连续 3 次失败后仍明确报错（实勘是否有限流/锁定）',
        shot: 'matrix/forum/07-login.png',
        neg: true,
      },
      {
        t: '删除他人评论 API 403（IDOR·身份交叉）',
        s: [
          'demo（demo@biomimic.app/demo123）与 r7other（r7other@t.com / Test1234!）分别登录各发一条评论，记下双方评论 id',
          '以 demo 身份在 UI 确认他人评论无删除按钮',
          '用 demo 的 JWT 直接 DELETE 他人评论 id（实勘 /api/comments/<id> 路由形态）',
        ],
        v: 'UI 无越权入口（删除按钮按作者渲染，v10 双向实测）；API 层 403、他人评论仍存在；作者本人与 super_admin 可删为已知白名单',
        shot: null,
        neg: true,
      },
      {
        t: '伪造 Bearer token 调发布评论 API（逆向·实勘）',
        s: [
          '构造无签名 token（Authorization: Bearer fake123）POST 评论发布接口',
          '对照：带真实 JWT 请求同一接口',
        ],
        v: '实勘：mock 后端历史上曾接受任意 user-token 自动登录——若 fake123 被放行记 P1（mock 认证旁路），若 401 则记录通过',
        shot: null,
        neg: true,
      },
      {
        t: 'Profile 渲染真实登录身份（v8 复验·正向）',
        s: ['登录 round2verify 后访问 /profile', '对照 localStorage 中 user.username'],
        v: '头像为用户名首字母、h1 为 round2verify；无 Jane Doe 硬编码残留（历史 P2 已修，复验防回归）',
        shot: null,
        neg: false,
      },
    ],
  },
  {
    portalId: 'forum',
    zh: '社区论坛',
    name: 'Forum',
    site: 'https://forum.lpm1.top',
    identity: '游客（未登录）',
    pos: 15,
    neg: 16,
    cases: [
      {
        t: '浏览内容列表',
        s: ['直接打开首页'],
        v: '公开内容可见',
        shot: 'matrix/forum/01-home.png',
        neg: false,
      },
      {
        t: '发帖/评论被拒',
        s: ['尝试发帖或评论（需登录）'],
        v: '被要求登录',
        shot: null,
        neg: true,
      },
      {
        t: '首页全景（2026-09-12 补拍）',
        s: ['直接打开首页，等待渲染'],
        v: '标题/筛选胶囊/搜索框/2 张卡片完整',
        shot: 'matrix/forum/forum-10.png',
        neg: false,
      },
      {
        t: '筛选"文章"类',
        s: ['点击第 2 个筛选胶囊'],
        v: '胶囊高亮，仅 1 卡（欢迎文章）',
        shot: 'matrix/forum/forum-11.png',
        neg: false,
      },
      {
        t: '搜索 ISR',
        s: ['先点回"全部"再搜索 ISR（搜索不重置分类）'],
        v: '仅 ISR 教程卡',
        shot: 'matrix/forum/forum-12.png',
        neg: false,
      },
      {
        t: '详情页全貌',
        s: ['点开欢迎文章进详情'],
        v: '面包屑/徽标/正文完整；徽标显示原始 key 未本地化（已知）',
        shot: 'matrix/forum/forum-13.png',
        neg: false,
      },
      {
        t: 'Topics 页',
        s: ['导航点击 Topics'],
        v: '⚠ 与首页完全相同（复用内容中心，无独立话题视图）',
        shot: 'matrix/forum/forum-14.png',
        neg: false,
      },
      {
        t: 'Popular 页',
        s: ['导航点击 Popular'],
        v: '⚠ 与首页完全相同，数据全 0 排序无可见效果',
        shot: 'matrix/forum/forum-15.png',
        neg: false,
      },
      {
        t: 'Profile 无鉴权守卫（逆向）',
        s: ['登出后访问 /profile'],
        v: '⚠ BUG：无守卫直接渲染 Jane Doe 硬编码档案',
        shot: 'matrix/forum/forum-16.png',
        neg: true,
      },
      {
        t: '登录页（逆向：假报错）',
        s: ['直接打开 /login 不做任何操作'],
        v: '⚠ P1 BUG：加载即显示 Invalid credentials（未提交过）',
        shot: 'matrix/forum/forum-17.png',
        neg: true,
      },
      {
        t: '注册页表单',
        s: ['从登录页点 Sign up 链接'],
        v: 'Create Account 表单完整（min 6 chars 校验提示）',
        shot: 'matrix/forum/forum-18.png',
        neg: false,
      },
      {
        t: '404 路由兜底',
        s: ['访问 /no-such-page-xyz'],
        v: 'HTTP 200 灰字 404；P3：无返回首页链接',
        shot: 'matrix/forum/forum-19.png',
        neg: true,
      },
      {
        t: '移动端首页（375px）',
        s: ['切 375x812 视口', '打开首页'],
        v: '胶囊换行/搜索堆叠/无横向溢出；⚠ 移动端无登录登出入口',
        shot: 'matrix/forum/forum-24-mobile.png',
        neg: false,
      },
      {
        t: '移动端详情页',
        s: ['375px 打开详情'],
        v: '纵向堆叠正常，底部 tab 正常',
        shot: 'matrix/forum/forum-25-mobile.png',
        neg: false,
      },
      {
        t: '移动端登录页（假报错复现）',
        s: ['375px 打开 /login'],
        v: '⚠ 同桌面：加载即 Invalid credentials',
        shot: 'matrix/forum/forum-26-mobile.png',
        neg: true,
      },
      {
        t: '登录横幅桌面复现 + 成功登录对照',
        s: ['桌面打开 /login 截假报错', '同凭据点 Sign In'],
        v: '假报错存在但手动登录成功（自动鉴权尝试失败泄入 UI）',
        shot: 'matrix/forum/forum-30.png',
        neg: false,
      },
      {
        t: '空分类筛选空态',
        s: ['点击"公告"胶囊'],
        v: '显示"暂无内容"空态文案',
        shot: 'matrix/forum/forum-31.png',
        neg: false,
      },
      {
        t: '游客态无评论管理按钮（逆向）',
        s: ['登出后打开内容详情评论区'],
        v: '可见评论列表但无任何删除按钮，显示"登录后参与讨论"引导',
        shot: null,
        neg: true,
      },
      {
        t: '真游客态工艺链（前置·自动登录怪癖）',
        s: [
          '全新会话打开首页（mock 后端会自动写入 auth-token/Demo User）',
          'eval 写入 localStorage.setItem("auth-token", JSON.stringify({state:{token:null,isAuthenticated:false,user:null},version:0})) 后 reload',
          '依次打开首页与内容详情确认身份',
        ],
        v: 'navbar 稳定显示 Login（键存在则不再自动登录，v9 实测工艺）；详情页评论区出现游客灰条——本用例为后续游客逆向用例的统一前置',
        shot: null,
        neg: true,
      },
      {
        t: '游客评论区只读态（v9 复验扩展）',
        s: [
          '真游客态打开 /content/content-1',
          '滚动到 [data-testid="comment-section"]',
          '点击灰条内的登录按钮',
        ],
        v: '无输入框无发布按钮；灰条"登录后参与讨论，分享你的想法"+登录按钮，点击跳转 /login；评论条目可见但 0 个删除按钮',
        shot: null,
        neg: true,
      },
      {
        t: '分类胶囊 6 连切遍历（正向遍历）',
        s: ['依次点击 6 个筛选胶囊：全部→文章→公告→教程→新闻→政策→全部'],
        v: '高亮跟随点击；文章=1 卡、教程=1 卡（ISR）、公告=暂无内容空态、新闻/政策=空态（实勘）、回到全部恢复 2 卡',
        shot: 'matrix/forum/forum-11.png',
        neg: false,
      },
      {
        t: '搜索大小写与中英混合（正向深化）',
        s: ['搜索小写 isr', '清空后搜索"教程"', '清空后搜索"欢迎"（content-1 标题词）'],
        v: '实勘：小写 isr 是否命中 ISR 教程（大小写不敏感则命中）；中文关键词是否覆盖标题/正文；无结果时显示暂无内容空态且关键词保留在输入框',
        shot: 'matrix/forum/forum-12.png',
        neg: false,
      },
      {
        t: '搜索后切换分类（组合语义边界）',
        s: [
          '搜索 ISR 得到 1 卡',
          '点击"公告"胶囊观察结果',
          '点击"全部"胶囊观察结果',
          '再次点击搜索按钮重搜',
        ],
        v: '实勘组合语义：切公告后是否空态、切回全部是否保留 ISR 关键词结果（已知 v4 观察"搜索不重置分类"，若行为相反记回归）；全程无 500/白屏',
        shot: null,
        neg: false,
      },
      {
        t: '空搜索直接提交（逆向边界）',
        s: ['不输入任何内容直接点击搜索按钮', '输入后再清空，再次提交'],
        v: '实勘：无提交动作或回退全列表；不出现 500/白屏，列表状态可恢复正常操作',
        shot: null,
        neg: true,
      },
      {
        t: '超长搜索词 256+（逆向）',
        s: ['在搜索框粘贴 300 字符无意义字符串并提交'],
        v: '不崩溃：显示空态或 0 结果；输入框无异常行为；提交后页面可继续正常搜索与筛选',
        shot: null,
        neg: true,
      },
      {
        t: '搜索 XSS/SQL 注入串（逆向）',
        s: ['搜索 <script>alert(1)<\/script> 并提交', "再搜索 ' OR 1=1 -- 并提交"],
        v: '关键词在空态文案中转义显示、无脚本执行；服务端不 500（防注入）；清空后列表恢复正常',
        shot: null,
        neg: true,
      },
      {
        t: '游客直访 /topics 与 /popular（入口正向）',
        s: ['地址栏直接打开 /topics', '再直接打开 /popular'],
        v: 'Topics 渲染独立聚合视图（h1 Topics、组头 "# 分类名"+绿色计数徽章）；Popular 渲染排行列表（排名徽章+🔥热度+热度条，热度 0 时条宽 0%）——v9 改版后两者均非首页复刻',
        shot: null,
        neg: true,
      },
      {
        t: '登录页假报错冷验回归（逆向·v7 修复防回归）',
        s: [
          '清空 localStorage 全新冷开 /login，静置 2s',
          '检查 [data-testid="login-error"] 与页面全部文本',
        ],
        v: '无 Invalid credentials 横幅（v6 旧缺陷见历史截图对照）；未提交任何表单前 error 区不渲染',
        shot: 'matrix/forum/forum-17.png',
        neg: true,
      },
      {
        t: '404 页游客态导航完整性（边界）',
        s: ['访问 /no-such-page-xyz', '检查 navbar/footer 与页面内容'],
        v: 'HTTP 200 灰字 404 兜底；navbar/footer 正常可点击回首页；已知 P3：无"返回首页"链接（保持记录）',
        shot: 'matrix/forum/forum-19.png',
        neg: true,
      },
      {
        t: '移动端底部 tab 遍历+游客登录条（375px）',
        s: [
          '375x812 视口打开内容首页',
          '依次点底部 tab Home/Topics/Popular/Profile',
          '观察导航下方 [data-testid="mobile-auth-bar"]，点击 Sign In 进入 /login 后返回首页',
        ],
        v: 'bottom-tab-home 落 /topics；各 tab 可达无 404；mobile-auth-bar 游客态显示 Sign In/Sign Up（v8 round4 冷验通过）；桌面导航在 375px 隐藏为已知',
        shot: 'matrix/forum/forum-24-mobile.png',
        neg: true,
      },
      {
        t: '游客伪造 token 调写 API（身份交叉·实勘）',
        s: [
          '真游客态（auth-token 置 null）直接 POST /api/contents 与评论发布接口（不带 Authorization）',
        ],
        v: '实勘：预期 401（写操作需登录/管理员）；若 mock 放行记 P1——该 mock 后端存在任意 token 放行的历史怪癖',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'shop',
    zh: '电商交易',
    name: 'Ecommerce',
    site: 'https://shop.lpm1.top',
    identity: '游客/消费者（唯一身份）',
    pos: 29,
    neg: 15,
    cases: [
      {
        t: '浏览内容中心',
        s: ['直接打开首页'],
        v: '内容卡片 + 分类 tab + 搜索框',
        shot: 'matrix/shop/shop-01.png',
        neg: false,
      },
      {
        t: '分类筛选',
        s: ['点击"教程"分类 tab'],
        v: '列表缩至仅教程类',
        shot: 'matrix/shop/shop-02.png',
        neg: false,
      },
      {
        t: '搜索',
        s: ['输入 ISR', '点击搜索'],
        v: '命中 ISR 教程',
        shot: 'matrix/shop/shop-03.png',
        neg: false,
      },
      {
        t: '查看内容详情',
        s: ['点击内容卡片'],
        v: '详情页完整',
        shot: 'matrix/shop/shop-04.png',
        neg: false,
      },
      {
        t: '购物车页面',
        s: ['点击导航 Cart'],
        v: 'mock 商品 + Order Summary + Checkout 按钮',
        shot: 'matrix/shop/shop-06.png',
        neg: false,
      },
      {
        t: '订单页面',
        s: ['点击导航 Orders'],
        v: 'mock 订单列表 + 状态筛选',
        shot: 'matrix/shop/shop-05.png',
        neg: false,
      },
      {
        t: '首页全景（2026-09-12 补拍）',
        s: ['直接打开首页，等待 SPA 渲染'],
        v: '导航 5 项 + 6 个分类 tab + 2 张内容卡片 + 页脚技术栈',
        shot: 'matrix/shop/shop-11.png',
        neg: false,
      },
      {
        t: '分类筛选后列表',
        s: ['点击"教程" tab', '等待列表刷新'],
        v: '教程 tab 高亮，列表仅剩 1 张 ISR 教程卡',
        shot: 'matrix/shop/shop-12.png',
        neg: false,
      },
      {
        t: '搜索关键词结果',
        s: ['输入 ISR', '点击搜索'],
        v: '1 卡命中，关键词保留在输入框',
        shot: 'matrix/shop/shop-13.png',
        neg: false,
      },
      {
        t: '内容详情页（逆向：导航高亮错乱）',
        s: ['点开 ISR 教程进入 /content/content-2'],
        v: '⚠ BUG：顶部导航 Account 被错误点亮（SSR 直出即带错）',
        shot: 'matrix/shop/shop-14.png',
        neg: true,
      },
      {
        t: '购物车实况（数据漂移：非空态）',
        s: ['点击导航 Cart'],
        v: '3 行 4 件 mock 商品，Total $188.96，Checkout 可点',
        shot: 'matrix/shop/shop-15.png',
        neg: false,
      },
      {
        t: '加入购物车（逆向：入口缺失）',
        s: ['在购物车页与详情页全量扫描加购/购买按钮'],
        v: '⚠ BUG：全站无任何加购/购买入口，电商闭环断裂',
        shot: 'matrix/shop/shop-15.png',
        neg: true,
      },
      {
        t: '订单页实况（数据漂移：非空态）',
        s: ['点击导航 Orders'],
        v: '5 张 mock 订单（ORD-2024-001..005），状态 chips 可筛选',
        shot: 'matrix/shop/shop-17.png',
        neg: false,
      },
      {
        t: '404 兜底（逆向：soft-404）',
        s: ['直接访问 /nonexistent'],
        v: '⚠ BUG：HTTP 200 纯文本 404，无返回首页 CTA',
        shot: 'matrix/shop/shop-18.png',
        neg: true,
      },
      {
        t: '详情页滚动到底（互动区探测）',
        s: ['在详情页滚动到页面底部'],
        v: '页面无滚动余量：无评论/推荐/点赞互动区',
        shot: 'matrix/shop/shop-19.png',
        neg: false,
      },
      {
        t: '搜索无结果空态',
        s: ['搜索乱码词 zzqqxx'],
        v: '0 卡，居中"暂无内容"，关键词保留',
        shot: 'matrix/shop/shop-20.png',
        neg: false,
      },
      {
        t: '详情页硬加载（SSR 验证）',
        s: ['在详情页按 F5 立即截图', '等 2s 截稳定帧对照'],
        v: '两帧一致：SSR 直出无白屏无骨架屏',
        shot: 'matrix/shop/shop-21.png',
        neg: false,
      },
      {
        t: '移动端首页（375px）',
        s: ['切 375x667 视口', '打开首页'],
        v: '顶部导航收起，底部 tab 栏（Home/Products/Cart/Orders/Me）',
        shot: 'matrix/shop/shop-22-home-mobile.png',
        neg: false,
      },
      {
        t: '移动端详情页（逆向：双高亮）',
        s: ['375px 打开详情页'],
        v: '⚠ BUG：Home 与 Me 同时高亮（home 恒高亮硬编码）；meta 中文拆行',
        shot: 'matrix/shop/shop-23-detail-mobile.png',
        neg: true,
      },
      {
        t: '移动端购物车（底部 tab 导航）',
        s: ['点击 bottom-tab-cart'],
        v: '购物车完整渲染，qty 步进器可用；Home 仍恒高亮',
        shot: 'matrix/shop/shop-24-cart-mobile.png',
        neg: false,
      },
      {
        t: '移动端导航形态实证',
        s: ['点击 bottom-tab-orders'],
        v: '⚠ BUG 实证：home tab inline style 恒高亮（computed style 双橙）',
        shot: 'matrix/shop/shop-25-nav-mobile.png',
        neg: false,
      },
      {
        t: '加购→下单→订单生成（正向闭环）',
        s: ['详情页加入购物车', 'Cart 页点击 Checkout', '导航切换到 Orders'],
        v: '生成 ORD-2026-xxxxxx 新订单（Processing 状态），购物车清空，旧 ORD-2024 mock 全部下线',
        shot: null,
        neg: false,
      },
      {
        t: '订单状态筛选',
        s: ['Orders 页点击 Processing 筛选 chip'],
        v: '新订单在 Processing 下可见，Delivered 筛选下隐藏并显示空态',
        shot: null,
        neg: false,
      },
      {
        t: '空购物车 Checkout 无效（逆向）',
        s: ['清空购物车后尝试 Checkout'],
        v: '无 Checkout 入口或点击无效果，不产生空订单',
        shot: null,
        neg: true,
      },
      {
        t: '详情页返回列表（正向）',
        s: ['打开 ISR 教程详情 /content/content-2', '点击"← 返回内容列表"'],
        v: '回到内容中心，列表与筛选状态不丢',
        shot: 'matrix/shop/shop-04.png',
        neg: false,
      },
      {
        t: '搜索 + 分类筛选组合（正向）',
        s: ['点击"教程"分类 tab', '在搜索框输入 ISR 并搜索'],
        v: '组合条件下仅命中 ISR 教程卡，无跨类结果',
        shot: 'matrix/shop/shop-13.png',
        neg: false,
      },
      {
        t: '分类连续切换（正向）',
        s: ['依次点击 文章 → 教程 → 全部 tab'],
        v: '每次切换列表即时刷新且 tab 高亮正确，切回全部恢复 2 卡',
        shot: 'matrix/shop/shop-02.png',
        neg: false,
      },
      {
        t: '刷新后购物车状态保持（正向）',
        s: ['进入 Cart 记录行数与 Total', '按 F5 硬刷新'],
        v: '刷新后仍 3 行 4 件、Total $188.96（mock 态持久），布局不乱',
        shot: 'matrix/shop/shop-15.png',
        neg: false,
      },
      {
        t: '购物车 qty 步进器加减（正向深化）',
        s: ['在 Cart 对任一行点击 qty +1', '观察小计与 Total', '再点击 qty -1 恢复'],
        v: '数量/小计/Total 随步进正确增减后复原',
        shot: 'matrix/shop/shop-15.png',
        neg: false,
      },
      {
        t: 'Products 导航同源验证（正向边界）',
        s: ['点击导航 Products'],
        v: '/products 渲染同一内容中心且 Products 高亮（与首页同源）',
        shot: 'matrix/shop/shop-07-products-nav.png',
        neg: false,
      },
      {
        t: '订单状态筛选切换（正向）',
        s: ['Orders 页依次点击 Shipped → Delivered → All 筛选 chip'],
        v: '每个筛选下订单集合正确（5 张 mock 单分布合理），All 恢复全量',
        shot: 'matrix/shop/shop-17.png',
        neg: false,
      },
      {
        t: '订单 Reorder 按钮探测（正向实勘）',
        s: ['在 Delivered 订单上点击 Reorder'],
        v: '实勘：记录跳转/反馈行为（不 500 不白屏），作为基线记录',
        shot: 'matrix/shop/shop-17.png',
        neg: false,
      },
      {
        t: '移动端搜索结果页（正向边界）',
        s: ['切 375x667 视口，搜索 ISR'],
        v: '结果单卡纵向堆叠正常无横向溢出',
        shot: null,
        neg: false,
      },
      {
        t: '购物车 qty=-1（逆向）',
        s: ['在 Cart 将某行 qty 连续点 - 至最小值', '尝试注入 -1（若输入框可编辑）'],
        v: '数量不为负（min 1 或步进禁用），Total 永不为负',
        shot: 'matrix/shop/shop-15.png',
        neg: true,
      },
      {
        t: '购物车 qty=9999 超大数量（逆向）',
        s: ['将某行 qty 调至 9999（步进连点或输入）'],
        v: '实勘：接受则 Total 大数正常显示不溢出；有上限则被钳制——记录行为',
        shot: null,
        neg: true,
      },
      {
        t: '搜索框 XSS 注入（逆向）',
        s: ['搜索框输入 <script>alert(1)<\/script> 并搜索'],
        v: '关键词按文本处理不执行（无弹窗），呈现空结果态',
        shot: 'matrix/shop/shop-20.png',
        neg: true,
      },
      {
        t: '搜索纯空格关键词（逆向）',
        s: ['搜索框输入多个空格并提交'],
        v: '不触发假搜索或显示空态，列表不闪空，无报错',
        shot: null,
        neg: true,
      },
      {
        t: '搜索超长关键词（逆向）',
        s: ['粘贴 256+ 字符长串搜索'],
        v: '输入框/结果区不撑破布局，空态正常',
        shot: null,
        neg: true,
      },
      {
        t: '详情 URL 不存在 id（逆向·IDOR 面）',
        s: ['直接访问 /content/content-999'],
        v: '空态/404 文案渲染，HTTP 状态记录（soft-404 已知），不暴露他人资源',
        shot: 'matrix/shop/shop-18.png',
        neg: true,
      },
      {
        t: 'Account 死链导航（逆向·已知缺陷）',
        s: ['点击导航 Account'],
        v: '⚠ 已知缺陷：Account 为死链，渲染 404 - Page not found',
        shot: 'matrix/shop/shop-08-account-404.png',
        neg: true,
      },
      {
        t: '双击 Checkout 重复下单（逆向）',
        s: ['在 Cart 快速双击 Checkout'],
        v: '实勘：仅生成 1 笔订单（若重复记录为缺陷），购物车状态一致',
        shot: null,
        neg: true,
      },
      {
        t: 'Checkout 后空购物车刷新保持（正向闭环深化）',
        s: ['完成 Checkout 进入 Cart', '按 F5 硬刷新'],
        v: '实勘：清空态保持不回填 mock 商品（若回填记录为缺陷）',
        shot: null,
        neg: false,
      },
      {
        t: '伪造 token 调订单写接口（逆向·API 级）',
        s: [
          'curl -X POST -H "Authorization: Bearer fake-token123" https://shop.lpm1.top/api/orders',
        ],
        v: '实勘：此形态无鉴权模块（公开站为预期）——记录写接口是否开放，若开放记录为风险',
        shot: null,
        neg: true,
      },
      {
        t: '分类 tab 快速连点（逆向·竞态）',
        s: ['快速连续点击多个分类 tab（文章/教程/公告连点）'],
        v: '最终停在最后点击的分类，列表与高亮一致，无竞态错乱',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'minimal',
    zh: '极简骨架',
    name: 'Minimal',
    site: 'https://minimal.lpm1.top',
    identity: '游客（唯一身份，无认证模块）',
    pos: 11,
    neg: 5,
    cases: [
      {
        t: '浏览 todos 列表',
        s: ['直接打开首页'],
        v: 'Todos 列表 + 极简导航（仅 Biomimic+Todos）',
        shot: 'matrix/minimal/01-home.png',
        neg: false,
      },
      {
        t: '新增 todo',
        s: ['在输入框填写标题', '点击 Add'],
        v: 'Total +1，新条目置顶',
        shot: 'matrix/minimal/02-add-new.png',
        neg: false,
      },
      {
        t: '输入中状态（按钮可用性）',
        s: ['聚焦输入框并输入标题（不提交）'],
        v: 'Add Todo 由 disabled 变可用',
        shot: 'matrix/minimal/minimal-06-add-input.png',
        neg: false,
      },
      {
        t: '新增后列表置顶',
        s: ['提交新增'],
        v: '新条目置顶，Total 12→13，输入框清空',
        shot: 'matrix/minimal/minimal-07-added-top.png',
        neg: false,
      },
      {
        t: '状态切换为 completed',
        s: ['下拉选择 completed'],
        v: '卡片变绿 + 标题划线 + 绿勾',
        shot: 'matrix/minimal/minimal-08-completed.png',
        neg: false,
      },
      {
        t: '删除条目',
        s: ['点击删除'],
        v: '立即移除（无确认弹窗），Total 13→12',
        shot: 'matrix/minimal/minimal-09-after-delete.png',
        neg: false,
      },
      {
        t: '移动端 375px',
        s: ['切 375x812 视口', '打开首页'],
        v: '无横向溢出；已知 P3：过滤 chips 右缘截断',
        shot: 'matrix/minimal/minimal-10-home-mobile.png',
        neg: false,
      },
      {
        t: '空标题提交无效（逆向）',
        s: ['不输入任何内容直接点击 Add'],
        v: '按钮禁用或提交无效果，不产生空标题条目',
        shot: null,
        neg: true,
      },
      {
        t: '状态切换后改回 pending（正向链）',
        s: ['下拉选择 completed', '再改回 pending'],
        v: '先变绿+划线，改回后恢复普通样式，无残留样式',
        shot: 'matrix/minimal/minimal-08-completed.png',
        neg: false,
      },
      {
        t: '刷新后列表与状态保持（正向）',
        s: ['记录当前列表与某条状态', '按 F5 硬刷新'],
        v: '刷新后列表条目与状态和刷新前一致，Total 计数不变',
        shot: 'matrix/minimal/01-home.png',
        neg: false,
      },
      {
        t: '连续添加 3 条（正向批量链）',
        s: ['连续 3 次输入不同标题并点击 Add'],
        v: 'Total +3，三条按序置顶，测试后逐条删除清理（与 todo 站共享后端）',
        shot: 'matrix/minimal/02-add-new.png',
        neg: false,
      },
      {
        t: 'emoji/中英混合标题正常提交（正向）',
        s: ['输入 🚀 上线 Release Notes 中英混合 标题', '点击 Add', '确认后删除清理'],
        v: '条目正常显示无乱码无报错，清理后恢复基线',
        shot: null,
        neg: false,
      },
      {
        t: '纯空格标题提交（逆向）',
        s: ['输入框只输入多个空格', '观察 Add 按钮状态并尝试提交'],
        v: 'Add 保持 disabled 或提交无效果（trim 守卫），不产生空标题条目',
        shot: null,
        neg: true,
      },
      {
        t: '超长标题提交（逆向）',
        s: ['粘贴 256+ 字符长串标题', '点击 Add'],
        v: '实勘：接受则卡片换行不撑破布局且 Total +1；拒绝则校验提示——记录行为',
        shot: null,
        neg: true,
      },
      {
        t: 'XSS 注入标题转义验证（逆向）',
        s: ['标题输入 <script>alert(1)<\/script>，点击 Add', '查看卡片渲染'],
        v: '纯文本渲染不执行（无弹窗），随后删除清理',
        shot: null,
        neg: true,
      },
      {
        t: '双击 Add 防重（逆向）',
        s: ['输入标题后快速双击 Add 按钮'],
        v: '仅新增 1 条（若重复记录为缺陷），随后清理',
        shot: null,
        neg: true,
      },
    ],
  },
  {
    portalId: 'cli',
    zh: 'CLI 工具',
    name: 'CLI Only',
    site: '',
    identity: 'CLI 用户（唯一身份）',
    pos: 4,
    neg: 4,
    cases: [
      {
        t: 'CLI 命令',
        s: ['npm run cli -- --help', '运行 todos list 等命令'],
        v: '命令输出正常',
        shot: null,
        neg: false,
      },
      {
        t: 'API 调用',
        s: ['curl http://localhost:3010/api/todos'],
        v: 'API 返回 JSON 数据',
        shot: null,
        neg: false,
      },
      {
        t: '未知命令报错（逆向）',
        s: ['npm run cli -- not-a-real-command'],
        v: '输出未知命令错误与用法提示，非静默成功',
        shot: null,
        neg: true,
      },
      {
        t: '访问不存在 API（逆向）',
        s: ['curl http://localhost:3010/api/not-exist'],
        v: '返回 404，不泄露堆栈',
        shot: null,
        neg: true,
      },
      {
        t: 'todos add→list→delete CLI 闭环（正向链）',
        s: [
          'npm run cli -- todos add "qa-e2e-chain-item"',
          'npm run cli -- todos list',
          'npm run cli -- todos delete <id>',
        ],
        v: 'list 输出包含新条目，删除后再 list 不再出现',
        shot: null,
        neg: false,
      },
      {
        t: 'CLI help 探测（正向）',
        s: ['npm run cli -- --help', 'npm run cli -- todos --help'],
        v: '两级用法输出完整（命令列表与子命令说明），退出码 0',
        shot: null,
        neg: false,
      },
      {
        t: '伪造 Bearer token 调写接口（逆向）',
        s: [
          'curl -X POST -H "Authorization: Bearer fake-token123" http://localhost:3010/api/todos',
        ],
        v: '返回 401，不产生任何待办数据',
        shot: null,
        neg: true,
      },
      {
        t: 'API 非法 payload 批量探测（逆向）',
        s: [
          'POST /api/todos 依次提交三种 payload：空标题 {"title":""}、超长 256+ 字符标题、<script>alert(1)<\/script> 注入标题',
        ],
        v: '每个 payload 均被 400/422 拒绝（或记录转义存储行为），绝不 500 不崩溃',
        shot: null,
        neg: true,
      },
    ],
  },
]
