export interface ModuleDefinition {
  label: string
  description: string
  category: 'basic' | 'ai' | 'ops' | 'tenant' | 'security'
  requires: string[]

  files: {
    server: string[]
    shared: string[]
    dbSchema: string[]
    dbSeeds: string[]
    clientPages: string[]
    clientStores: string[]
    clientComponents: string[]
    clientHooks: string[]
    opsPages: string[]
    opsComponents: string[]
    opsHooks: string[]
    opsStores: string[]
    opsServices: string[]
    tenantFiles: string[]
    platformFiles: string[]
    cliModules: string[]
  }

  references: {
    routeRegistry: { importLines: number[]; routeLines: number[] }
    dbSchemaIndex: number[]
    sharedSchemasIndex: number[]
    sharedModulesIndex: number[]
    clientApp: { importLines: number[]; routeLines: number[] }
    opsApp: { importLines: number[]; routeLines: number[] }
    clientNavigation: string[]
  }

  dependencies: Record<string, string>
  devDependencies: Record<string, string>
}

export const moduleRegistry: Record<string, ModuleDefinition> = {
  todos: {
    label: '待办事项',
    description: 'Todo CRUD、文件附件',
    category: 'basic',
    requires: [],
    files: {
      server: [
        'module-todos/routes/todos-routes.ts',
        'module-todos/services/todo-service.ts',
        'module-todos/__tests__/todos-route-rpc.test.ts',
        'module-todos/__tests__/todo-service.test.ts',
        'module-todos/__tests__/todos-file-upload.test.ts',
      ],
      shared: ['todos/index.ts', 'todos/schemas.ts'],
      dbSchema: ['todos.ts', 'todo-attachments.ts'],
      dbSeeds: [],
      clientPages: ['TodoPage.tsx'],
      clientStores: ['todoStore.ts'],
      clientComponents: [],
      clientHooks: [],
      opsPages: [],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: ['todo/index.ts'],
    },
    references: {
      routeRegistry: { importLines: [2], routeLines: [22] },
      dbSchemaIndex: [1, 2],
      sharedSchemasIndex: [
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
      ],
      sharedModulesIndex: [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
      clientApp: { importLines: [3], routeLines: [24] },
      opsApp: { importLines: [], routeLines: [] },
      clientNavigation: ['todos'],
    },
    dependencies: {},
    devDependencies: {},
  },

  chat: {
    label: '实时聊天',
    description: 'WebSocket 聊天、消息协议',
    category: 'ai',
    requires: [],
    files: {
      server: [
        'module-chat/routes/chat-routes.ts',
        'module-chat/services/chat-service.ts',
        'module-chat/__tests__/chat-routes.test.ts',
        'module-chat/__tests__/chat-rpc.test.ts',
        'module-chat/__tests__/chat-service.test.ts',
      ],
      shared: ['chat/index.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: ['WebSocketPage.tsx'],
      clientStores: ['chatWSStore.ts'],
      clientComponents: ['MessageCard.tsx'],
      clientHooks: [],
      opsPages: [],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [7], routeLines: [20] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [22, 23, 24, 25, 26, 27],
      sharedModulesIndex: [1],
      clientApp: { importLines: [5], routeLines: [26] },
      opsApp: { importLines: [], routeLines: [] },
      clientNavigation: ['websocket'],
    },
    dependencies: {
      ws: '^8.18.3',
    },
    devDependencies: {
      '@types/ws': '^8.18.0',
    },
  },

  notifications: {
    label: '通知系统',
    description: 'SSE 推送通知、未读计数',
    category: 'basic',
    requires: [],
    files: {
      server: [
        'module-notifications/routes/notification-routes.ts',
        'module-notifications/services/notification-service.ts',
        'module-notifications/__tests__/notification-route-rpc.test.ts',
        'module-notifications/__tests__/notification-service.test.ts',
        'module-notifications/__tests__/sse-rpc.test.ts',
      ],
      shared: ['notifications/index.ts', 'notifications/schemas.ts'],
      dbSchema: ['notifications.ts'],
      dbSeeds: [],
      clientPages: ['NotificationPage.tsx'],
      clientStores: ['notificationStore.ts'],
      clientComponents: [],
      clientHooks: [],
      opsPages: [],
      opsComponents: ['NotificationDrawer.tsx'],
      opsHooks: ['useOpsNotifications.ts'],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: ['notification/index.ts'],
    },
    references: {
      routeRegistry: { importLines: [6], routeLines: [21] },
      dbSchemaIndex: [3],
      sharedSchemasIndex: [
        57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
      ],
      sharedModulesIndex: [52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
      clientApp: { importLines: [4], routeLines: [25] },
      opsApp: { importLines: [], routeLines: [] },
      clientNavigation: ['notifications'],
    },
    dependencies: {},
    devDependencies: {},
  },

  file: {
    label: '文件管理',
    description: '文件上传下载、存储服务',
    category: 'basic',
    requires: [],
    files: {
      server: [
        'module-file/routes/file-routes.ts',
        'module-file/__tests__/file-routes.test.ts',
        'module-file/__tests__/file-storage-service.test.ts',
      ],
      shared: ['files/index.ts', 'files/schemas.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: [],
      clientStores: [],
      clientComponents: ['FilePreview.tsx', 'FileTree.tsx', 'TreeNode.tsx'],
      clientHooks: [],
      opsPages: [],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [14], routeLines: [35] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [28, 29, 30, 31, 32, 33, 34, 35, 36],
      sharedModulesIndex: [43, 44, 45, 46, 47, 48, 49, 50, 51],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: { importLines: [], routeLines: [] },
      clientNavigation: [],
    },
    dependencies: {},
    devDependencies: {},
  },

  agent: {
    label: 'AI Agent',
    description: 'AI 对话、工作空间、SSE 流式输出',
    category: 'ai',
    requires: [],
    files: {
      server: [
        'module-agent/index.ts',
        'module-agent/types.ts',
        'module-agent/routes/agent-routes.ts',
        'module-agent/routes/file-routes.ts',
        'module-agent/routes/workspace-routes.ts',
        'module-agent/services/agent-service.ts',
        'module-agent/services/chat-service.ts',
        'module-agent/services/chat-session-manager.ts',
        'module-agent/services/file-service.ts',
        'module-agent/services/llm-service.ts',
        'module-agent/services/mock-service.ts',
        'module-agent/services/paths.ts',
        'module-agent/services/sandbox-bash.ts',
        'module-agent/services/session-parser.ts',
        'module-agent/services/sse-manager.ts',
        'module-agent/services/workspace-service.ts',
        'module-agent/services/types.ts',
        'module-agent/__tests__/agent-routes.test.ts',
        'module-agent/__tests__/agent-service.test.ts',
        'module-agent/__tests__/sandbox-security.test.ts',
        'module-agent/__tests__/workspace-routes.test.ts',
        'module-agent/data/mock/error.jsonl',
        'module-agent/data/mock/search.jsonl',
        'module-agent/data/mock/scenarios.json',
        'module-agent/data/mock/hello.jsonl',
      ],
      shared: ['agent/index.ts', 'agent/schemas.ts', 'agent/pi-types.ts'],
      dbSchema: ['agents.ts', 'workspaces.ts'],
      dbSeeds: [],
      clientPages: ['ChatPage.tsx'],
      clientStores: ['agentStore.ts', 'workspaceStore.ts'],
      clientComponents: [
        'ChatArea.tsx',
        'ChatInput.tsx',
        'MessageList.tsx',
        'PendingMessages.tsx',
        'CommandPalette.tsx',
        'DynamicButton.tsx',
        'LazyMonacoEditor.tsx',
        'WorkspacePanel.tsx',
        'RoundCard.tsx',
      ],
      clientHooks: [
        'useChat.ts',
        'useChatSSEConnection.ts',
        'useScrollLoading.ts',
        'useCommands.ts',
        'useTypewriter.ts',
      ],
      opsPages: [],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [16], routeLines: [24, 25, 26] },
      dbSchemaIndex: [11, 12],
      sharedSchemasIndex: [],
      sharedModulesIndex: [
        2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31,
      ],
      clientApp: { importLines: [6], routeLines: [27] },
      opsApp: { importLines: [], routeLines: [] },
      clientNavigation: ['chat'],
    },
    dependencies: {
      '@anthropic-ai/sandbox-runtime': '^0.0.42',
      '@mariozechner/pi-coding-agent': '^0.61.0',
      '@monaco-editor/react': '^4.7.0',
      'react-markdown': '^10.1.0',
      'remark-gfm': '^4.0.1',
      vm2: '^3.10.5',
    },
    devDependencies: {
      'monaco-editor': '^0.55.1',
      'vite-plugin-monaco-editor': '^1.1.0',
    },
  },

  permission: {
    label: '权限管理',
    description: 'RBAC 权限、角色、审计日志',
    category: 'security',
    requires: ['ops'],
    files: {
      server: [
        'module-permission/routes/permission-routes.ts',
        'module-permission/routes/role-routes.ts',
        'module-permission/routes/audit-log-routes.ts',
        'module-permission/services/permission-service.ts',
        'module-permission/services/permission-service-impl.ts',
        'module-permission/services/role-service.ts',
        'module-permission/services/audit-log-service.ts',
        'module-permission/__tests__/permission-routes.test.ts',
        'module-permission/__tests__/permission-service.test.ts',
        'module-permission/__tests__/permission-service-impl.test.ts',
        'module-permission/__tests__/role-routes.test.ts',
        'module-permission/__tests__/permission-middleware.test.ts',
      ],
      shared: [],
      dbSchema: [
        'permissions.ts',
        'roles.ts',
        'role-permissions.ts',
        'user-roles.ts',
        'api-endpoints.ts',
        'permission-route-mappings.ts',
        'permission-audit-logs.ts',
      ],
      dbSeeds: ['permission-data.ts'],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: ['PermissionsPage.tsx', 'RolesPage.tsx'],
      opsComponents: ['PermissionConfigEditor.tsx', 'PermissionGuard.tsx', 'PermissionTree.tsx'],
      opsHooks: ['usePermissions.ts', 'useRoles.ts', 'useAuditLogs.ts'],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: ['shared/permission/', 'shared/audit/'],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [3, 4, 5], routeLines: [37, 38, 39] },
      dbSchemaIndex: [4, 5, 6, 7, 8, 9, 10],
      sharedSchemasIndex: [],
      sharedModulesIndex: [
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
        102, 103, 104, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
      ],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: { importLines: [8, 9], routeLines: [48, 49] },
      clientNavigation: [],
    },
    dependencies: {},
    devDependencies: {},
  },

  ops: {
    label: '运营后台',
    description: '运营管理面板、仪表盘、用户管理',
    category: 'ops',
    requires: ['permission'],
    files: {
      server: [
        'module-ops/routes/ops-routes.ts',
        'module-ops/routes/user-management-routes.ts',
        'module-ops/routes/system-routes.ts',
        'module-ops/routes/ops-notification-routes.ts',
        'module-ops/routes/media-routes.ts',
        'module-ops/routes/export-routes.ts',
        'module-ops/routes/auth-routes.ts',
        'module-ops/services/admin-service.ts',
        'module-ops/services/ticket-service.ts',
        'module-ops/services/order-service.ts',
        'module-ops/services/dispute-service.ts',
        'module-ops/services/content-service.ts',
        'module-ops/__tests__/admin-service.test.ts',
        'module-ops/__tests__/admin-routes.test.ts',
        'module-ops/__tests__/ticket-service.test.ts',
        'module-ops/__tests__/order-service.test.ts',
        'module-ops/__tests__/dispute-service.test.ts',
        'module-ops/__tests__/content-service.test.ts',
      ],
      shared: ['ops/index.ts', 'ops/schemas.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: [
        'DashboardPage.tsx',
        'LoginPage.tsx',
        'RegisterPage.tsx',
        'SettingsPage.tsx',
        'StaffPage.tsx',
        'SystemLogsPage.tsx',
        'UsersPage.tsx',
        'MediaTestPage.tsx',
        'TestCaptchaPage.tsx',
      ],
      opsComponents: [
        'AccountSwitcher.tsx',
        'StatsCard.tsx',
        'PageHeader.tsx',
        'UserFormModal.tsx',
        'UserTable.tsx',
      ],
      opsHooks: ['useConfig.ts'],
      opsStores: ['opsStore.ts', 'loadingStore.ts'],
      opsServices: ['apiClient.ts', 'requestInterceptor.ts', 'types.ts'],
      tenantFiles: [],
      platformFiles: ['shared/settings/', 'server/module-settings/'],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [8], routeLines: [40] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [],
      sharedModulesIndex: [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: {
        importLines: [4, 5, 6, 7, 10, 11, 16],
        routeLines: [38, 39, 44, 45, 46, 47, 48, 49],
      },
      clientNavigation: [],
    },
    dependencies: {
      antd: '^5.24.0',
    },
    devDependencies: {},
  },

  order: {
    label: '订单管理',
    description: '订单 CRUD、状态流转',
    category: 'ops',
    requires: ['ops'],
    files: {
      server: [
        'module-order/routes/order-routes.ts',
        'module-order/services/order-service.ts',
        'module-order/__tests__/order-route.test.ts',
        'module-order/__tests__/order-service.test.ts',
      ],
      shared: ['order/index.ts', 'order/schemas.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: ['OrdersPage.tsx'],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [10], routeLines: [31] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [],
      sharedModulesIndex: [],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: { importLines: [12], routeLines: [40] },
      clientNavigation: [],
    },
    dependencies: {},
    devDependencies: {},
  },

  ticket: {
    label: '工单系统',
    description: '工单管理、回复、状态流转',
    category: 'ops',
    requires: ['ops'],
    files: {
      server: [
        'module-ticket/routes/ticket-routes.ts',
        'module-ticket/services/ticket-service.ts',
        'module-ticket/__tests__/ticket-route.test.ts',
        'module-ticket/__tests__/ticket-service.test.ts',
      ],
      shared: ['ticket/index.ts', 'ticket/schemas.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: ['TicketsPage.tsx'],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [11], routeLines: [32] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [],
      sharedModulesIndex: [],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: { importLines: [13], routeLines: [41] },
      clientNavigation: [],
    },
    dependencies: {},
    devDependencies: {},
  },

  dispute: {
    label: '争议处理',
    description: '争议管理、解决流程',
    category: 'ops',
    requires: ['ops'],
    files: {
      server: [
        'module-dispute/routes/dispute-routes.ts',
        'module-dispute/services/dispute-service.ts',
        'module-dispute/__tests__/dispute-route.test.ts',
        'module-dispute/__tests__/dispute-service.test.ts',
      ],
      shared: ['dispute/index.ts', 'dispute/schemas.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: ['DisputesPage.tsx'],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [12], routeLines: [33] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [],
      sharedModulesIndex: [],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: { importLines: [14], routeLines: [42] },
      clientNavigation: [],
    },
    dependencies: {},
    devDependencies: {},
  },

  content: {
    label: '内容管理',
    description: 'CMS 内容管理、富文本',
    category: 'ops',
    requires: ['ops'],
    files: {
      server: [
        'module-content/routes/content-routes.ts',
        'module-content/services/content-service.ts',
        'module-content/__tests__/content-route.test.ts',
        'module-content/__tests__/content-service.test.ts',
      ],
      shared: ['content/index.ts', 'content/schemas.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: ['ContentPage.tsx'],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [13], routeLines: [34] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [],
      sharedModulesIndex: [],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: { importLines: [15], routeLines: [43] },
      clientNavigation: [],
    },
    dependencies: {},
    devDependencies: {},
  },

  tenant: {
    label: '多租户',
    description: '租户管理、成员、角色、邀请',
    category: 'tenant',
    requires: ['permission'],
    files: {
      server: [
        'module-tenant/index.ts',
        'module-tenant/routes/tenant-routes.ts',
        'module-tenant/services/tenant-service.ts',
        'module-tenant/__tests__/tenant-routes.test.ts',
        'module-tenant/__tests__/tenant-service.test.ts',
      ],
      shared: ['tenant/schemas.ts'],
      dbSchema: ['tenants.ts', 'tenant-roles.ts', 'tenant-members.ts', 'tenant-invitations.ts'],
      dbSeeds: ['tenant-data.ts'],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: [],
      opsComponents: [],
      opsHooks: [],
      opsStores: [],
      opsServices: [],
      tenantFiles: [
        'pages/TenantListPage.tsx',
        'pages/TenantCreatePage.tsx',
        'pages/TenantPage.tsx',
        'pages/MembersPage.tsx',
        'pages/RolesPage.tsx',
        'pages/SettingsPage.tsx',
        'pages/BillingPage.tsx',
        'pages/InviteAcceptPage.tsx',
        'pages/index.ts',
        'layouts/TenantLayout.tsx',
        'layouts/TenantHeader.tsx',
        'layouts/TenantSidebar.tsx',
        'layouts/index.ts',
        'stores/tenantStore.ts',
        'services/tenantApi.ts',
      ],
      platformFiles: ['tenant/index.ts'],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [15], routeLines: [23] },
      dbSchemaIndex: [14, 15, 16, 17],
      sharedSchemasIndex: [],
      sharedModulesIndex: [],
      clientApp: {
        importLines: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        routeLines: [29, 30, 31, 32, 33, 34, 35, 36, 37, 39],
      },
      opsApp: { importLines: [], routeLines: [] },
      clientNavigation: ['tenants'],
    },
    dependencies: {},
    devDependencies: {},
  },

  captcha: {
    label: '验证码',
    description: '图形验证码、频率限制',
    category: 'security',
    requires: [],
    files: {
      server: [
        'module-captcha/routes/captcha-routes.ts',
        'module-captcha/services/captcha-service.ts',
        'module-captcha/__tests__/captcha-route.test.ts',
        'module-captcha/__tests__/captcha-service.test.ts',
      ],
      shared: ['captcha/index.ts', 'captcha/schemas.ts'],
      dbSchema: [],
      dbSeeds: [],
      clientPages: [],
      clientStores: [],
      clientComponents: [],
      clientHooks: [],
      opsPages: [],
      opsComponents: ['CaptchaModal.tsx'],
      opsHooks: [],
      opsStores: ['captchaStore.ts'],
      opsServices: [],
      tenantFiles: [],
      platformFiles: [],
      cliModules: [],
    },
    references: {
      routeRegistry: { importLines: [9], routeLines: [36] },
      dbSchemaIndex: [],
      sharedSchemasIndex: [],
      sharedModulesIndex: [],
      clientApp: { importLines: [], routeLines: [] },
      opsApp: { importLines: [16], routeLines: [56] },
      clientNavigation: [],
    },
    dependencies: {},
    devDependencies: {},
  },
}
