#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running TypeScript type check..."
npm run typecheck

echo "Running all tests..."
npm run test

echo "Running template tests..."
npm run test -- --config template/vitest.config.ts

npx lint-staged
